### ISSUE TITLE
Tab or C-i cannot be mapped

### ISSUE THREAD

**Issue by pyluyten** [ergoemacs/ergoemacs-mode#217]
C-i stands for tab. I want to map this however, and this works fine, for example if i define my own minor mode.

If i define C-I with global set key inside an ergoemacs theme (or within one of its components), then <tab> actually does... tab.

This is surprising since ^h k says"【↹Tab】 runs the command previous-line" which is fine. But actually it does not call this function.

**Comment by mlf176f2** [comment]
This now works in the current unstable version of ergoemacs-mode.
