### ISSUE TITLE
Arrow keys return A B C D

### ISSUE THREAD

**Issue by rainbyte** [ergoemacs/ergoemacs-mode#280]
Hi.

I've installed ergoemacs-mode and arrow keys suddenly stopped working.
They return characters A B C and D when are pressed. 

Tested with konsole and gnome-terminal, on Arch Linux.
I'm using emacs 24.3 with ergoemacs-mode 5.17.7.2.

**Comment by balsoft** [comment]
@mattfidler this happens for me with emacs 26.3 and ergoemacs 20181127.1330 . The snippet above doesn't seem to work.
