### ISSUE TITLE
Cannot generate the cheat sheet

### ISSUE THREAD

**Issue by ghost** [ergoemacs/ergoemacs-mode#291]
I tried just now to generate the cheat sheet but the following error message was displayed on the
minibuffer:

"/usr/bin/emacs" -Q --batch -l /home/marcos/.emacs.d/ergoemacs-mode//ergoemacs-mode -l /tmp/ergoemacs-gen1788dQJ.el: exited abnormally with code 255.

I cloned the git repository today. After doing a M-a ergoemacs-clean I tried to generate the cheat
sheet again. The output in the _Messages_ buffer was the following:

Ergoemacs-mode turned ON.
Wrong number of arguments: ((cua--last-killed-rectangle cua--register org-table-any-line-regexp ergoemacs-mode helm-ff-last-expanded helm-ff-default-directory helm-buffer ergoemacs-single-command-keys font-lock cua--rectangle ...) nil "Generates the current ergoemacs layout, unless it already exists and opens it in a browser.
With a prefix, force regeneration. " (interactive) (let\* ((var (or ergoemacs-theme "standard")) (layout ergoemacs-keyboard-layout) (extra (concat var "/ergo-layouts")) (md5 (if ergoemacs-theme--object (concat "-" (ergoemacs-theme-component-map-list-md5 ergoemacs-theme--object)) "")) (dir (expand-file-name extra (expand-file-name "ergoemacs-extras" user-emacs-directory))) (png (expand-file-name (concat "ergoemacs-layout-" layout md5 ".png") dir)) (file (expand-file-name (concat "ergoemacs-layout-" layout md5 ".svg") dir))) (if (and (not current-prefix-arg) (file-exists-p file)) nil (if (called-interactively-p (quote any)) (let ((temp-file (make-temp-file "ergoemacs-gen" nil ".el"))) (let ((temp-file temp-file) (temp-buffer (get-buffer-create (generate-new-buffer-name " _temp file_")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert ...) (let ... ...) (insert ")
(ergoemacs-mode 1)
(ergoemacs-display-current-svg 1)")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (shell-command (format "%s -Q --batch -l %s/ergoemacs-mode -l %s &" (ergoemacs-emacs-exe) ergoemacs-dir temp-file))) (message "Generating SVG file...") (if (featurep (quote ergoemacs-extras)) nil (require (quote ergoemacs-extras))) (ergoemacs-gen-svg layout "kbd-ergo.svg" extra) (message "Generated!"))) (if (file-exists-p png) (progn (setq file png))) (if (not (file-exists-p file)) (message "Need to generate/download layout.") (if (called-interactively-p (quote interactive)) (progn (condition-case err (browse-url-of-file file) (error (message "Error opening with browser (%s), try opening in an external app." err) (ergoemacs-open-in-external-app file)))))) file)), 1
Saving file /home/marcos/.recentf...
Wrote /home/marcos/.recentf
Saving file /home/marcos/.recentf...
Wrote /home/marcos/.recentf
Ergoemacs-mode turned OFF.

I am using Emacs 24.3.1 on Slackware64. I hope I included all the relevant information to diagnose
the problem.

**Comment by mattfidler** [comment]
Which version of ergoemacs-mode are you using?

**Comment by cblp** [comment]
ergoemacs-mode-5.14.7.3. My Emacs says it it latest version.
