### ISSUE TITLE
It's Slowing down my Emacs

### ISSUE THREAD

**Issue by shahinism** [ergoemacs/ergoemacs-mode#315]
Hi, it seems that ergoemacs is slowing down my emacs too much. When I open a file with more than hundred lines, the cursor will glitch while moving around. It also affected my Emacs startup time. Is there anyway to reduce some of ergoemacs functionality and get my speed back? 

I just have a regular installation.

**Comment by xahlee** [comment]
ugh, just saw this. Hope all's well...

**Comment by mlf176f2** [comment]
I've been strapped for time, but the branch that takes care of the speed issues is nearer completion.  Isearch is working well.  I'm still having troubles with setting up ergoemacs-keys at the right time for major modes.  There is no standard for when the keys are setup.

**Comment by mlf176f2** [comment]
The lastest unstable master branch addresses this issue.

It speeds up ergoemacs-mode by the following:
- Using the package unicode-fonts to cache and enhance the unicode capabilities of ergoemacs-mode.  

The first startup is brutal of this package is brutal, but it saves time after initial startup. In ergoemacs-mode it only sets up the enhanced unicode support if this has been cached.  

See https://github.com/rolandwalker/unicode-fonts for more information.

ergoemacs-mode also now caches the keymap lookups for your configuration (and will invalidate the cache when it detects a configuration change).  For me, this makes my initial startup time for emacs-mode key lookups ~ 14 seconds and the subsequent startup ~1 second.  It also makes my interactive emacs sessions much more responsive.  

Therefore, now I'm going to close this issue.

**Comment by meteficha** [comment]
I've installed the lastest unstable from ELPA.  Why is it contacting ELPA on every startup?  Is my setup wrong?

**Comment by meteficha** [comment]
For future reference:  I had a line explicitly enabling ergoemacs.  Removing it made everything work fine (so far).  :)

**Comment by meteficha** [comment]
Sorry for the spam: @mlf176f2 I had to manually install `smex` otherwise `M-a` wouldn't work.

**Comment by mlf176f2** [comment]
Smex shouldn't be required...  When I run from a clean environment (`C-h z`), smex isn't installed and `M-a` works (It shows `M-x` but that is a separate issue)
