### ISSUE TITLE
key binding of isearch-forward changed after start a eshell buffer  

### ISSUE THREAD

**Issue by magichowl** [ergoemacs/ergoemacs-mode#322]
In my emacs with ergoemacs, isearch forward is binding to \C-f and \M-y,.

However, the keys are changed to command "eshell-isearch-repeat-forward" after eshell started.

This bug doesn't appear if I **do not** require ergoemacs, so I post a issue here.

**Comment by mlf176f2** [comment]
Added test, and it passes interactively in emacs 24.3
