### ISSUE TITLE
Ergoemacs-mode keybinding not working in multi-term

### ISSUE THREAD

**Issue by erreina** [ergoemacs/ergoemacs-mode#324]
Hi, I am using ergoemacs-mode and I would like to use its keybinding for cursor movement on multi-term. However, when pressing <M-j> I get printed the character 'ê', similar with almost all other keybindings. I have installed ergoemacs-mode and multi-term using el-get.

**Comment by mlf176f2** [comment]
This may be fixed in the current branch.  It dose respect the input-method (and passes a test about it).  I canot figure out how to test this, so I will be closing it unless you tell me the unstable version doesn't work.
