### ISSUE TITLE
set-key on specifik hook not working with ergoemacs

### ISSUE THREAD

**Issue by codebold** [ergoemacs/ergoemacs-mode#325]
The following code does not set the keybinding as expected if ergoemacs-mode is active on my emacs.
```lisp
    (add-hook 'server-switch-hook
              (lambda ()
                [...]
                (global-set-key (kbd "C-w") 'server-edit))
    )
```

Is there a reason for this or a way to come around this issue? Thanks!

**Comment by mlf176f2** [comment]
Yes.  there are many ways to overcome this issue.  One of the easiest is 

```
    (add-hook 'server-switch-hook
              (let ((ergoemacs-is-user-defined-map-change-p t))
           (lambda ()
                [...]
                (global-set-key (kbd "C-w") 'server-edit))))
```

Another possibility is to make it a theme component.  See https://groups.google.com/forum/#!topic/ergoemacs/iFOLu5tHHkY

**Comment by mlf176f2** [comment]
It is actually a bug, by the way.  I'm working on fixing it.  I'm a bit swamped currently.

**Comment by codebold** [comment]
Thanks for your fast reply and your advice. However I was not able to get things going... Your proposal with (ergoemacs-is-user-defined-map-change-p t) didn't change the behavior and I'm also struggling with the theme-component approach. If i add the following code:

    (ergoemacs-theme-component ergoemacs-server ()
      "Emacs server"
      (when server-switch-hook
        (message "### server-switch-hook ###")
        (global-set-key global-map (kbd "C-w") 'server-edit)))
    
    (ergoemacs-require 'ergoemacs-server)

I can see the message in my Messages buffer, so the hook gets active, but the keybinding is still not applied...

I would really appreciate any further suggestions.

**Comment by mlf176f2** [comment]
Thanks @codebold 

You could do any of the following:

```lisp
(global-set-key (kbd "C-w") 'server-edit)
```

```lisp
(define-key global-map (kbd "C-w") 'server-edit)
```

Or by a theme component:

```lisp
  (ergoemacs-theme-component ergoemacs-server ()
      "Emacs server"
     (global-set-key global-map (kbd "C-w") 'server-edit))

    (ergoemacs-require 'ergoemacs-server)
```

They typical `ergoemacs-server` command is bound globally.  There is no keymap to modify for this command, so a global binding would work just fine. 

I'm unsure what the purpose is of defining it only after the server is setup...Do you want to close the buffer after editing lt with emacs?  If so, I think this may be what many users would like, and I should redefine close buffer to take care of server buffers...

**Comment by mlf176f2** [comment]
This modification should allow Ctrl+w to close the server-editing session if it started, and then maintain the close buffer functionality elsewhere...

I don't use the server-edit component too much, if you decide to use this, let me know if it works.

**Comment by codebold** [comment]
You're right, the reason was to close server-editing session (http://www.emacswiki.org/emacs/EmacsClient#toc36). It would be great if ergoemacs would provide this functionality. 

Unfortunately the recent changes did not work for me. I obtain ergoemacs from elpa, so the version on my machine is 'ergoemacs-mode-20141101.158'. I tried do add your changes manually to the file 'ergoemacs-functions.el', but with no effect (still receive "Buffer `xyz' still has clients; kill it? (y or n)" on close). So i cloned the repository and included ergoemacs directly. But, whenever i started emacsclients it was shutdown automatically and the terminal showed up again, so that i restored my previous configuration. 

However, as the changes worked at your machine, its very likely that my configuration is somewhat demolished. So I will try it with a minimal configuration as soon as possible and report the outcome. Thanks for all your efforts!

**Comment by mlf176f2** [comment]
@codebold I actually didn't try it out, I just thought it would work.  I also think the other approach I just committed should work, but I work in windows so every time I try to stat a client it opens a new frame.

**Comment by codebold** [comment]
This time you nailed it! So far, it works like a charm. Many thanks again. Your work is greatly appreciated.

**Comment by mlf176f2** [comment]
Great.  Thank you for testing this for me.

**Comment by mlf176f2** [comment]
I suggest you update again, othrewise killing the buffer may not work correctly.

**Comment by codebold** [comment]
Thanks!
