### ISSUE TITLE
alt key error

### ISSUE THREAD

**Issue by wolfand11** [ergoemacs/ergoemacs-mode#326]
my ergoemacs-mode config:
```lisp
(setq ergoemacs-theme nil)
(setq ergoemacs-keyboard-layout "us")
(require 'ergoemacs-mode)
(ergoemacs-mode 1)
```

problem:
when i input alt+g alt+g, "©©" is insert into buffer. all alt+any key is insert some special char into buffer

my emacs version:
GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org

**Comment by mlf176f2** [comment]
I'm sorry, I can't reproduce this since I don't have a mac.


Are you using the stable version of eroemacs?

https://github.com/ergoemacs/ergoemacs-mode/releases

**Comment by wolfand11** [comment]
this is my version info : 
     Status: Installed in `~/Documents/MyCore/Config/EmacsConfig/Plugin/elpa/ergoemacs-mode-20150113.1313/' (unsigned).
    Archive: n/a
    Version: 20150113.1313
   Requires: emacs-24.1, undo-tree-0.6.5
    Summary: Emacs mode based on common modern interface and ergonomics.
   Homepage: https://github.com/ergoemacs/ergoemacs-mode
   Keywords: convenience 
    Other versions: 20150114.809 (melpa), 5.14.7.3 (gnu).

i install with melpa

**Comment by wolfand11** [comment]
i uninstall the ergoemacs-mode-20150113.1313 then install version 5.14.7.3, alt+anykey still error

**Comment by mlf176f2** [comment]
What about the stable with stable emacs 24.3 or 24.4?

On Jan 15, 2015 8:32 PM, "wolfand11" <notifications@github.com> wrote:
>
> i uninstall the ergoemacs-mode-20150113.1313 then install version
5.14.7.3, alt+anykey still error

**Comment by wolfand11** [comment]
after i removed ergoemacs-mode, the alt key worked.

**Comment by wolfand11** [comment]
@mlf176f2 
i try ergoemacs-mode in windows7,it's ok

in osx, ergoemacs changed my .emacs config. it append below config in my .emacs config.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ergoemacs-ctl-c-or-ctl-x-delay 0.2)
 '(ergoemacs-handle-ctl-c-or-ctl-x (quote both))
 '(ergoemacs-ini-mode t)
 '(ergoemacs-keyboard-layout "us")
 '(ergoemacs-mode nil)
 '(ergoemacs-smart-paste nil)
 '(ergoemacs-theme "standard")
 '(ergoemacs-theme-options nil)
 '(ergoemacs-use-menus t)
 '(initial-frame-alist (quote ((fullscreen . maximized))))
 '(initial-scratch-message
   ";; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.

")
 '(org-CUA-compatible nil)
 '(org-replace-disputed-keys nil)
 '(org-special-ctrl-a/e nil)
 '(org-support-shift-select nil)
 '(recentf-menu-before "Open File...")
 '(scroll-error-top-bottom nil)
 '(set-mark-command-repeat-pop nil)
 '(shift-select-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

**Comment by wolfand11** [comment]
@mlf176f2  in windows the WIN key is disable and in osx the alt key is disable

**Comment by mlf176f2** [comment]
Ah, Alt doesn't work for `ergoemacs-mode` in mac osx.  Alt is replaced by the command key `⌘`.  This is because the command key is closest to the keyboard in mac OSX.  

The Alt is probably the super key (equivalent to the windows `⊞` key) .  You can change this by adding:

```lisp
(setq ergoemacs-use-mac-command-as-meta nil)
```

After you change either `ns-command-modifier`, or `mac-command-modifier` as well as `ns-alternate-modifier` or `mac-alternate-modifier` as you prefer.

**Comment by mlf176f2** [comment]
See 
- http://ergoemacs.org/emacs/emacs_hyper_super_keys.html
- http://xahlee.info/kbd/apple_pc_kb_diff.html

**Comment by wolfand11** [comment]
@mlf176f2 
(setq ergoemacs-use-mac-command-as-meta nil) is ok! thank you very much!

**Comment by wolfand11** [comment]
ergoemacs of osx platform changed my .emacs config. it append below config in my .emacs config. and i must move my config for ergoemacs to .emacs, put it behind below config.

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ergoemacs-ctl-c-or-ctl-x-delay 0.2)
 '(ergoemacs-handle-ctl-c-or-ctl-x (quote both))
 '(ergoemacs-ini-mode t)
 '(ergoemacs-keyboard-layout "us")
 '(ergoemacs-mode nil)
 '(ergoemacs-smart-paste nil)
 '(ergoemacs-theme "standard")
 '(ergoemacs-theme-options nil)
 '(ergoemacs-use-menus t)
 '(initial-frame-alist (quote ((fullscreen . maximized))))
 '(initial-scratch-message
   ";; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.

")
 '(org-CUA-compatible nil)
 '(org-replace-disputed-keys nil)
 '(org-special-ctrl-a/e nil)
 '(org-support-shift-select nil)
 '(recentf-menu-before "Open File...")
 '(scroll-error-top-bottom nil)
 '(set-mark-command-repeat-pop nil)
 '(shift-select-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

**Comment by mlf176f2** [comment]
This is because `ergoemacs-mode` saves all the "user-defined" changes to the custom file.

You can change this so it isn't your `.emacs` file by:

```lisp
(setq custom-file "~/.custom.el")
```

in your `.emacs` file
