### ISSUE TITLE
conflict with user "menu" key sequence

### ISSUE THREAD

**Issue by xahlee** [ergoemacs/ergoemacs-mode#332]
I have many key sequence starting with the "menu" key. But when ergoemacs is on, they don't work.
I don't think this is expected. What files, settings, should i report?
Thanks.

**Comment by mlf176f2** [comment]
Just one of the sequences that you setup that doesn't work.  Then I can create a test to fix it.

**Comment by xahlee** [comment]
here's a example.
(progn
(define-prefix-command 'xah-harmless-keymap)
(global-set-key (kbd "<menu> n") xah-harmless-keymap)
(define-key xah-harmless-keymap (kbd "e") 'eshell)
)

what's a way to disable all menu/app as lead key in ergoemacs mode? I think i'd be happy with that.

**Comment by mlf176f2** [comment]
Sorry, I didn't see your last comment.

You can remove all of the ergoemacs apps/menu lead keys in the global map by:
``lisp
(ergoemacs-remove '(apps apps-toggle apps-apps apps-punctuation apps-swap))
```

I personally would keep apps-swap since it changes the "stickieness" of keys in a keysequence so that it can be unchorded.

**Comment by xahlee** [comment]
Thanks Matt.
