### ISSUE TITLE
Cannot use some commands in Helm

### ISSUE THREAD

**Issue by tuhdo** [ergoemacs/ergoemacs-mode#337]
If I have a Helm command with multiple sources, I normally switch using `C-o`. However, it seems to be shadowed by file opening in Ergoemacs. Probably we should temporary disable Ergoemacs key bindings when a Helm session is alive, except for the predefined keys <kbd>Alt + i/j/k/l</kbd>?

Currently, I cannot go up a directory with <kbd>C-l</kbd> in `helm-find-files`. What `C-l` does is that it jump up a directory level, not deleting part of parent directory name.

**Comment by mlf176f2** [comment]
Currently `ergoemacs-mode` doesn't actually define the helm equivalents of <kbd>Alt+i/j/k/l</kbd>, it looks through the helm keymaps and redefines the keys based on ergoemacs-mode bindings, so disabling all the keys would be a bit more difficult.

The default global map uses <kbd>C-o</kbd> for `open-line`.  This is different from the open line you describe in #339 (It appears the community is segmented on this issue).  If you defined a ergoemacs-mode theme option that includes `open-line`, then that command key would also switch between multiple sources.

If <kbd>C-o</kbd> makes more sense to open multiple sources in helm (which makes sense to me), it can also be defined to change to switch sources by `C-o` by an additional theme option.  Same with `C-l`.

**Comment by mlf176f2** [comment]
I have added an option to `ergoemacs-mode` to satisfy these two cases.
