### ISSUE TITLE
major mode's menu e key doesn't work

### ISSUE THREAD

**Issue by xahlee** [ergoemacs/ergoemacs-mode#341]
in a major mode, e.g. xah-html-mode, i have menu e as a start key for mode specific command. (that is, similar to emacs using C-c for mode specific)

this menu e doesn't seem to work when ergoemacs-mode is loaded and this setting
;; disable all ergoemacs-mode apps/menu lead keys
(ergoemacs-remove '(apps apps-toggle apps-apps apps-punctuation apps-swap))

**Comment by mlf176f2** [comment]
I think this should work in the latest unstable.
