### ISSUE TITLE
Incompatibility between ergoemacs-mode and pdf-tools

### ISSUE THREAD

**Issue by CallumCameron** [ergoemacs/ergoemacs-mode#344]
With ergoemacs-mode and pdf-tools installed, many actions (such as pressing `C-h k` or `<end>`) result in `lisp nesting exceeds 'max-lisp-eval-depth'`, and then all keys get unbound, and Emacs must be forcibly killed. This happens with the current version of ergoemacs-mode in MELPA, but not the older version in MELPA Stable. I am using Emacs 24.5.1 on Linux Mint 17.1, ergoemacs-mode 20150318.1413 from MELPA, and pdf-tools 20150526.55 from MELPA (though the same thing happens with the MELPA Stable version of pdf-tools, too).

Minimal working example: remove your .emacs and .emacs.d, open up Emacs, and evaluate:

    (require 'package)
    (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))

Then interactively install the packages: ergoemacs-mode (from MELPA), pdf-tools.

Then evaluate:

    (require 'pdf-tools)
    (require 'ergoemacs-mode)
    (ergoemacs-mode)

The debugger pops up with `lisp nesting exceeds 'max-lisp-eval-depth'` and Emacs becomes unresponsive.

**Comment by mlf176f2** [comment]
The master branch is currently unstable and will soon be replaced.   I have re-written most of ergoemacs-mode in the modify-maps-new-engine branch, which is starting to be stable enough to try to replace the current master branch.  For now the obvious work around is to use the stable release.

**Comment by CallumCameron** [comment]
OK, thanks.

**Comment by mlf176f2** [comment]
This seems to work with the current master branch.  I'm unsure if everything else works, but its a start.
