### ISSUE TITLE
How to unset <f6> in ergoemacs-mode

### ISSUE THREAD

**Issue by magichowl** [ergoemacs/ergoemacs-mode#349]
I rarely use <Alt+> command mode, and I want to make use of the key <f6>,

However, neither of the followings worked,
``` elisp
(global-unset-key (kbd "<f6>"))
```
``` elisp
(ergoemacs-theme-component pan ()
(global-unset-key (kbd "<f6>"))
)
```

**Comment by mlf176f2** [comment]
Have you tried global-set-key? I don't have access to a computer until
Monday.

**Comment by mlf176f2** [comment]
(global-set-key [f6] 'undefined) may work

**Comment by magichowl** [comment]
Matthew Fidler <notifications@github.com> writes:

> (global-set-key [f6] 'undefined) may work

Yes, it works.

However, I want to set a local-key for <f6>

``` elisp
(setq pdf-annot-minor-mode-map-prefix (kbd "<f6>"))
```
which is variable defined in pdf-tools mode

global key of [f6] override the local key, even set [f6] as undefined.

>
> On Sat, Aug 1, 2015, 3:32 PM Matthew Fidler <matthew.fidler@gmail.com>
> wrote:
>
>> Have you tried global-set-key? I don't have access to a computer
> until
>> Monday.
>>

**Comment by mlf176f2** [comment]
Did you make sure to add

(ergoemacs-require 'pan) after your theme component?

**Comment by magichowl** [comment]
Matthew Fidler <notifications@github.com> writes:

> Did you make sure to add
>
> (ergoemacs-require 'pan) after your theme component?

Yes, I added. Now the problem is when I view pdf files under
pdf-view-mode and press <f6>, the result is

"<f6> is undefined".

However, I want to enable local key binding of <f6> under pdf-view-mode.
``` elisp
(setq pdf-annot-minor-mode-map-prefix (kbd "<f6>"))
```

which unfortunately takes effect only when ergoemacs-mode is disabled.

**Comment by mlf176f2** [comment]
I have a fix for it in the unstable branch modify-maps-new-engine.

**Comment by mlf176f2** [comment]
Somehow there are some mark issues with the new fix.

**Comment by magichowl** [comment]
I've update my repo to the latest "modify-maps-new-engine", but nothing is changed.

**Comment by magichowl** [comment]
Not solved yet. 

The odd thing is if I enable ergoemacs-mode under "pdf-view-mode"

one kbd is
``` 
<ergoemacs-user> <f6> t
```
compared to
```
<f6> t
```
when ergoemacs-mode disabled.

**Comment by mlf176f2** [comment]
Are you sure you deleted  the old elc files.   The current implementation no longer uses the ergoemacs user key entries.

**Comment by magichowl** [comment]
Debugger entered--Lisp error: (setting-constant nil)
  set(nil nil)
  (progn (set hook (mapcar (function (lambda (fn) (if (or (eq fn t) (and ... ... ...)) fn (list (quote lambda) nil "Ergoemacs protect local" (list ... ... ...) (list ... ...))))) (symbol-value hook))))
  (if (boundp hook) (progn (set hook (mapcar (function (lambda (fn) (if (or ... ...) fn (list ... nil "Ergoemacs protect local" ... ...)))) (symbol-value hook)))))
  (if (consp hook) (let ((--dolist-tail-- hook)) (while --dolist-tail-- (let ((lhook (car --dolist-tail--))) (ergoemacs-map-properties--modify-run-mode-hooks lhook) (setq --dolist-tail-- (cdr --dolist-tail--))))) (if (boundp hook) (progn (set hook (mapcar (function (lambda (fn) (if ... fn ...))) (symbol-value hook))))))
  (let ((hook (car --dolist-tail--))) (if (consp hook) (let ((--dolist-tail-- hook)) (while --dolist-tail-- (let ((lhook (car --dolist-tail--))) (ergoemacs-map-properties--modify-run-mode-hooks lhook) (setq --dolist-tail-- (cdr --dolist-tail--))))) (if (boundp hook) (progn (set hook (mapcar (function (lambda ... ...)) (symbol-value hook)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (if (consp hook) (let ((--dolist-tail-- hook)) (while --dolist-tail-- (let ((lhook ...)) (ergoemacs-map-properties--modify-run-mode-hooks lhook) (setq --dolist-tail-- (cdr --dolist-tail--))))) (if (boundp hook) (progn (set hook (mapcar (function ...) (symbol-value hook)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (if (consp hook) (let ((--dolist-tail-- hook)) (while --dolist-tail-- (let (...) (ergoemacs-map-properties--modify-run-mode-hooks lhook) (setq --dolist-tail-- ...)))) (if (boundp hook) (progn (set hook (mapcar ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (let (tmp) (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (if (consp hook) (let ((--dolist-tail-- hook)) (while --dolist-tail-- (let ... ... ...))) (if (boundp hook) (progn (set hook ...)))) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  ergoemacs-map-properties--modify-run-mode-hooks(nil)
  ad-Advice-run-mode-hooks(#[128 "\203

**Comment by magichowl** [comment]
thanks, I use the branch v5.14.7.3.1, problem is solved.

**Comment by mlf176f2** [comment]
Thanks for the backtrace; it was useful.
