### ISSUE TITLE
Multilingual input methods don't work

### ISSUE THREAD

**Issue by m00natic** [ergoemacs/ergoemacs-mode#352]
Using ergoemacs-mode-20150814.1823 with either emacs-24.5 or today's
trunk (abd838e).  After M-x ergoemacs-clean:

Command
"/usr/bin/emacs-24.5" --debug-init -Q -L "/home/akotlarski/.emacs.d/elpa/ergoemacs-mode-20150814.1823/"  --load="ergoemacs-mode" --load="ergoemacs-test"  --eval "(progn (require 'elp) (setq debug-on-error t) (elp-instrument-package (symbol-name 'ergoemacs-)) (ergoemacs-mode 1) (run-with-idle-timer 0.1 nil 'elp-results))"

Ergoemacs-mode turned ON (colemak:standard).

C-\
(M-x toggle-input-method)

Now probably due to my locale I have bulgarian-bds as
default-input-method without explicit settings.  However, Latin
characters are inputed as before.

**Comment by mlf176f2** [comment]
I cannot figure out how to test this.  I don't have bulgarian-bds as an input method.  In fact I don't have any input methods.

**Comment by m00natic** [comment]
In the cleaned states, here's what you can do:

M-: (setq default-input-method nil)

now

C-\

will ask you for input method, tab-completion should work, choose
greek for example and press <a>, <b>.  The expected result is to see
alpha and beta characters, but in this case latin ab would come out.

**Comment by mlf176f2** [comment]
I really can't reproduce; for some reason  but I can read documentation.  Maybe the above fix works.  I got this idea by reading:

http://www.gnu.org/software/emacs/manual/html_node/elisp/Reading-One-Event.html#Reading-One-Event

**Comment by mlf176f2** [comment]
I don't have a list of any input methods available to me...  Something must be wrong about my emacs installation, or the input methods don't work in windows?

**Comment by mlf176f2** [comment]
Never mind.  I did get the input method working in emacs 24.5, and it seems to work for me.  Let me know if it works for you.

**Comment by mlf176f2** [comment]
The first character seems to be in latin and the rest seem to be in greek.  Is that expected?

**Comment by m00natic** [comment]
Maybe your font somehow picks latin because missing alpha.  Anyway,
works now, thank you!

**Comment by mlf176f2** [comment]
This should now also be fixed for people who use different keyboard layouts with non-latin punctuation.  (At least I think).

 http://www.emacswiki.org/emacs/WritingRussianWithDvorak

**Comment by mlf176f2** [comment]
I added a test and ergoemacs-mode now passes this test.  If you have any other problems please let me know.
