### ISSUE TITLE
ergoemacs-close-current-buffer can lead to infinite loop

### ISSUE THREAD

**Issue by m00natic** [ergoemacs/ergoemacs-mode#355]
emacs-24.5 with ergoemacs-mode-20150824.1237

The culprit is actually within ergoemacs-next-user-buffer which calls
(next-buffer) in a loop which may not end.

To reproduce after M-x ergoemacs-clean just press C-w on ELP results'
buffer.

**Comment by mlf176f2** [comment]
Should be fixed.  Now its not limited to 20 buffers to check.  Also can use a prefix argument.  Reopen this issue if it doesn't work for you.
