### ISSUE TITLE
'QUIT' must be an ASCII character

### ISSUE THREAD

**Issue by noahprince22** [ergoemacs/ergoemacs-mode#365]
On emacs 24.5, I'm installing ergoemacs in my .emacs file on OSx with:

    (use-package ergoemacs-mode
           :ensure ergoemacs-mode)
    (setq ergoemacs-theme nil)
    (setq ergoemacs-keyboard-layout "us")
    (ergoemacs-ignore-prev-global) ; Do not honor previously defined
                                            ; global keys.

    (ergoemacs-mode 1)

When I debug-init I'm getting this:

    Debugger entered--Lisp error: (error "QUIT must be an ASCII character")
      set-input-mode(t nil 0 (escape))
      apply(set-input-mode (t nil 0 (escape)))
      ergoemacs-command-loop--redefine-quit-key([escape])
      ergoemacs-command-loop--setup-quit-key()
      #<subr run-hooks>(ergoemacs-mode-startup-hook)
      apply(#<subr run-hooks> ergoemacs-mode-startup-hook)
      ad-Advice-run-hooks(#<subr run-hooks> ergoemacs-mode-startup-hook)
      apply(ad-Advice-run-hooks #<subr run-hooks> ergoemacs-mode-startup-hook)
      run-hooks(ergoemacs-mode-startup-hook)
      ergoemacs-mode(1)
      eval-buffer(#<buffer  *load*> nil "/Users/xxx/.emacs" nil t)      ; Reading at buffer position 9849
      load-with-code-conversion("/Users/xxx/.emacs"     "/Users/xxxxx/.emacs" t t)
      load("~/.emacs" t t)
      #[0 "^H\205\262^@ \306=\203^Q^@\307^H\310Q\202;^@         \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\3$
      command-line()
      normal-top-level()
    
This never used to happen on my old macbook, but is now happening on every computer I try it on.

**Comment by mlf176f2** [comment]
I will fix it later today.

**Comment by mlf176f2** [comment]
Should be fixed, with the same functionality you had before.

**Comment by mlf176f2** [comment]
You will need to update from melpa unstable
