### ISSUE TITLE
Horizontal window split missing

### ISSUE THREAD

**Issue by m00natic** [ergoemacs/ergoemacs-mode#373]
The usual horizontal split key-binding points to vertical split, using
emacs-24.5 with ergoemacs-mode-20151005.1440

To reproduce after ergoemacs-clean:

M-$

Expected is horizontal split, but vertical is done instead.  Indeed

C-h k M-$

says

Alt+$ (translated from ergoemacs-ignore) runs the command
split-window-below ...

**Comment by mattfidler** [comment]
You are right.  It has actually been annoying me.  I have reverted the switch component.
