### ISSUE TITLE
Impossible to register macros

### ISSUE THREAD

**Issue by anbasile** [ergoemacs/ergoemacs-mode#376]
I am using lvl2, with this in my dot-emacs

    (require 'ergoemacs-mode)
    (setq ergoemacs-theme "lvl2")
    (setq ergoemacs-keyboard-layout "it")
    (ergoemacs-mode 1)

I start registering a macro by pressing F3 and when I am finished and want to stop recording I press F4 (or `C-x )`) and I get "Ignore empty macro". If I remove ergo-mode it works perfectly.

**Comment by mattfidler** [comment]
This seems to be the same as #370.  Have you updated to the latest version of ergoemacs-mode?  I can run macros on the latest version of ergoemacs-mode.
