### ISSUE TITLE
Shortcut "M-a" bound to ergoemacs-cut-line-or-region by default

### ISSUE THREAD

**Issue by gamaralf** [ergoemacs/ergoemacs-mode#377]
After I start ergoemacs with "M-x ergoemacs-mode" (or (require 'ergoemacs-mode) ), then "M-a" is now bound to ergoemacs-cut-line-or-region as well as "M-x". I end up without a shortcut to "execute-extended-command" anymore.

I am using Emacs 24.3.1 and ergoemacs-mode version: 20151008.757 (via Melpa).

**Comment by mattfidler** [comment]
Thats very odd.  When I compile and call the clean ergoemacs-mode from 24.3 (under windows) M-a is `execute-extended-command`.

Have you tried cleaning the key cache?

This is done by removing everything in `~/.emacs.d/var/pcache/ergoemacs*.*` and then restarting emacs.

**Comment by mattfidler** [comment]
I also tried turning off ergoemacs-mode and turning it on again, and I can't reproduce this either.

**Comment by gamaralf** [comment]
My `~/.emacs.d/var/pcache/` is empty.

Besides `M-a`, there is other important shortcut that is not bound correctly: `C-s`. When I hit it, I get the warning: 
> Ctrl+S is disabled! Use Ctrl+F for isearch-forward instead.

I even tested it with a bare bones `~/.emacs`, containing only:
```
(when (>= emacs-major-version 24)
  (require 'package)
  (package-initialize)
  (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
  (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/")))
```

**Comment by mattfidler** [comment]
What packages do you have, other than `ergoemacs-mode`.  `package-initialize` isn't quite bare-bones depending on what packages you have installed.

Try deleting all the `.elc` files in `ergoemacs-mode` directory and restarting (also make sure there is only one ergoemacs-mode in the elpa directory as well as one `ergoemacs-mode` in the load path). Perhaps some of the macros changed enough to not correctly install keys when you restart.  

if you are in Unix and downloaded ergoemacs-mode from melpa, you can also try 

```sh
make start
```

in the ergoemacs-mode directory.  It should delete all the `.elc` files, recompile them and then start `ergoemacs-mode`.

**Comment by mattfidler** [comment]
FYI when I run `make start` I have `C-s` bound to `save-buffer`.

**Comment by gamaralf** [comment]
Running `make start` in `~/.emacs.d/elpa/ergoemacs-mode-20151008.757` does not work because there is no Makefile there. However after deleting manually all the `*.elc` and restarting emacs, the shortcuts (`M-a` and `M-s`) are working again! :smile:. Thanks.

**Comment by mattfidler** [comment]
You could also resinstall ergoemacs-mode afteward and it should also work with the `elc` files.

This is one of the idiosyncrasies of Emacs and macros.
