### ISSUE TITLE
Lisp nesting exceeds `max-lisp-eval-depth' when I try to look up the 'repeat-complex-command' function

### ISSUE THREAD

**Issue by wilsonywx** [ergoemacs/ergoemacs-mode#379]
I am getting this stackoverflow error when I try to look up the 'repeat-complex-command' function. See details below. 

How to reproduce: 
C-h f RET
repeat-complex-command RET

My setup: 
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil)
(ergoemacs-mode 1)

emacs version:
"GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian"

The stack trace: 
  ergoemacs-translate--event-modifiers(134217755)
  key-description([134217755])
  ergoemacs-translate--event-modifiers(134217755)
  key-description([134217755])
  ergoemacs-translate--event-modifiers(134217755)
  key-description([24 134217755])
  mapconcat(key-description ([again] [redo] [24 134217786] [24 134217755] [menu-bar file repeat-earlier-command]) ", ")
  help-fns--key-bindings(repeat-complex-command)
  describe-function-1(repeat-complex-command)
  describe-function(repeat-complex-command)
  call-interactively(describe-function t nil)
  ergoemacs-command-loop--call-interactively(describe-function t)
  ergoemacs-command-loop--execute(describe-function)
  #[0 "\302^Y\303\300@!)\207" [(describe-function) inhibit-quit nil ergoemacs-command-loop--execute] 2 "\n\n(fn)"]()
  funcall(#[0 "\302^Y\303\300@!)\207" [(describe-function) inhibit-quit nil ergoemacs-command-loop--execute] 2 "\n\n(fn)"])
  ergoemacs-command-loop--internal(nil nil nil nil)
  ergoemacs-command-loop()
  ergoemacs-command-loop-start()
  call-interactively(ergoemacs-command-loop-start nil nil)

**Comment by mattfidler** [comment]
Thanks.  I will look into it tomorrow

**Comment by wilsonywx** [comment]
Oh, and this is using the 20151029 version on melpa. When I use the version from gnu this problem does not occur.

**Comment by mattfidler** [comment]
I can also reproduce this by:

```lisp
(mapconcat #'ergoemacs-key-description '([again] [redo] [24 134217786] [24 134217755] [menu-bar file repeat-earlier-command]) ", ")
```

**Comment by mattfidler** [comment]
Or
```lisp
(ergoemacs-key-description [24 134217755])
``

**Comment by mattfidler** [comment]
Or 

```lisp
(ergoemacs-translate--event-modifiers 134217755)
```

**Comment by mattfidler** [comment]
This should be fixed now.
