### ISSUE TITLE
Unexcepted EOF

### ISSUE THREAD

**Issue by anbasile** [ergoemacs/ergoemacs-mode#383]
Error while executing "gzip -c -q -d < /home/angelo/.emacs.d/var/pcache/ergoemacs-mode-24-5-1-x86-64-unknown-linux-gnu.gz"

gzip: stdin: unexpected end of file

**Comment by mattfidler** [comment]
Try

```lisp

(setq ergoemacs--gzip nil)

```
before loading ergoemacs

**Comment by anbasile** [comment]
I haven't seen it anymore.
