### ISSUE TITLE
Kill-buffer

### ISSUE THREAD

**Issue by anbasile** [ergoemacs/ergoemacs-mode#384]
Is there any reason why <kbd>Ctrl</kbd>+<kbd>x</kbd> <kbd>k</kbd> is not disabled ?

Disabling original key mapping is great for speeding up learning the new on and I love it.

**Comment by mattfidler** [comment]
No reason.  I will change it soon.  Thanks for the catch.

**Comment by mattfidler** [comment]
Although <kbd>Ctrl</kbd>+<kbd>w</kbd> is not the most ergonomic...

**Comment by mattfidler** [comment]
Should be fixed.
