### ISSUE TITLE
Ctrl-s is somehow disabled

### ISSUE THREAD

**Issue by samis** [ergoemacs/ergoemacs-mode#388]
For some reason, my 'Ctrl-s' key is disabled, saying that I should use Ctrl-f for isearch-forward again. Problem is, I was trying to save a file not search it. Ctrl-S with capitals works though, but is less easy to type. Shouldn't Ctrl-s be bound to save-buffer/file even in lowercase?

**Comment by mattfidler** [comment]
Most definitely. Unfortunately my computer just died, so I cannot debug this right now.

**Comment by mattfidler** [comment]
Try commit 85aa1a54d166b5212ca13be48e2ed22c2f8adc3e.  It is the last commit to pass the Travis tests

**Comment by samis** [comment]
Found the issue. Issue #377 struck again. Perhaps it would be a good idea to examine why that bug occurs.

**Comment by mattfidler** [comment]
First I need to reproduce it...

**Comment by mattfidler** [comment]
Thanks for letting me know.

**Comment by mattfidler** [comment]
My guess is that the files are byte-compiled with an old version of ergoemacs-macros installed, and then there is incompatability between the versions causing fundamental keys like <kbd>Ctrl</kbd>+<kbd>s</kbd> to be corrupt.  I'm not sure how to work around this right now.  If you have any suggestions let me know.
