### ISSUE TITLE
A way to don't pollute custom set vars

### ISSUE THREAD

**Issue by kolya-ay** [ergoemacs/ergoemacs-mode#389]
Every time I install ergomacs-mode it writes it's setup to custom-variables. E.g.

    (custom-set-variables
     '(ergoemacs-ctl-c-or-ctl-x-delay 0.2)
     '(ergoemacs-handle-ctl-c-or-ctl-x (quote both))
     ...
     '(initial-scratch-message ...)

I want to remove this config and add my own customizations (`(setq ergoemacs-ctl-c-or-ctl-x-delay 0.2)`, etc). However if I delete set-custom-variables lines, the package adds it back on next restart. 

Is there a way to disable this?

**Comment by mattfidler** [comment]
I believe three is, but I can't remember the option offhand.. I won't have access to a computer until 4 Jan.

**Comment by xahlee** [comment]
meanwhile, you can simply add your own code after that auto-generated code.

e.g. add this
(setq ergoemacs-ctl-c-or-ctl-x-delay 0.2)
after that block.

**Comment by mattfidler** [comment]
That's true.

**Comment by mattfidler** [comment]
You can also customize the variable and it will save.

**Comment by kolya-ay** [comment]
Yes, I know, but I prefer to keep my `custom.el` clean as it is under source control. However if it is not possible, well, i accept it.

**Comment by mattfidler** [comment]
It's possible. I will make sure of it

**Comment by Valdaer** [comment]
Long time ago I had that problem too, I don't remember where I found solution but you must add
```
(setq ergoemacs-theme-options (quote ((save-options-on-exit off))))
```
line to your ergoemacs configuration/init.el

**Comment by kolya-ay** [comment]
@Valdaer thank you! That is exactly what I looking for!

**Comment by mattfidler** [comment]
Ergoemacs-mode no longer savea customize setting upon closing emacs.
