### ISSUE TITLE
Inclusion of Ctrl-X and Ctrl-C keybinds in the fancy generated images

### ISSUE THREAD

**Issue by samis** [ergoemacs/ergoemacs-mode#390]
so, I'm a big fan of the fancy diagrams generated which include the keybinds and show the actions associated to a key. Is it possible for this diagrams to optionally include actions using Ctrl-X or Ctrl-C prefixes? Would be nice to be able to generate the diagrams for themes that mix standard Emacs keybindings with ErgoEmacs keybindings.

**Comment by mattfidler** [comment]
Yes.  I belive the code is there, partially.  I will revisit it in a couple of weeks.

**Comment by mattfidler** [comment]
It may be included in ergo emacs describe theme...

**Comment by mattfidler** [comment]
The code to generate the images is there.  However, it can only be access by lisp.  

How do you currently view the images?

**Comment by mattfidler** [comment]
You should be able to call a prefix argument and describe a theme and show all the fancy diagrams for any key sequence including Ctrl+x and Ctrl+c
