### ISSUE TITLE
Can't re-enable C-SPC shortcut in .emacs - getting "Keybinding is disabled!"

### ISSUE THREAD

**Issue by pdg137** [ergoemacs/ergoemacs-mode#397]
This is very similar to Issue #296, though the specfic example in that Issue does still work for me.
 
I have had problems on recent version of Ergoemacs-mode, _only when running in an X window_,  evaluating the following:

```lisp
   (package-initialize)
   (ergoemacs-mode 1)
   (global-set-key (kbd "C-SPC") 'set-mark-command)
```

If (after running `emacs -q`) I run those lines with `M-x eval-buffer` or `M-x eval-region`, the keybinding doesn't work, instead returning the annoying message

    Ctrl+Space is disabled! Use Ctrl-@ for set-mark-command instead.

I can succeed by evaluating the last line manually, but this means I can't do this kind of customization in my init file.  I suspect that Ergoemacs is doing some delayed processing that includes "disabling" some keybindings that I am trying to use.

Very strangely, when running Emacs in terminal mode with `emacs -q -nw`, evaluating that buffer does the right thing.

I am using ergoemacs-mode-20160114.1028 from melpa and Emacs 24.3.1 on Ubuntu 14.04.

**Comment by mattfidler** [comment]
Hm.  I will look into it.

**Comment by pdg137** [comment]
In case it helps, another command that doesn't work in my init file (but works fine when run later) is

    (define-key isearch-mode-map (kbd "M-;") 'isearch-repeat-forward)

**Comment by mattfidler** [comment]
Do you have anything in `~/.emacs.d/var/pcach/ergoemacs-*`?

**Comment by mattfidler** [comment]
Also did you delete all the `elc` files,restart and then recompile.  Both those things have been causing problems for people.

**Comment by pdg137** [comment]
Removing pcache AND reinstalling ergoemacs-mode fiixed this and Issue #400.!

**Comment by timseries** [comment]
I am having this issue, even after reinstalling ergoemacs-mode. Mptjomgom ~/.emacs.d/var/pcache/ergoemacs-*. 

 Can also evaluate 
```
(global-set-key (kbd "C-SPC") 'set-mark-command)
```
manually and then it works.

**Comment by mattfidler** [comment]
Reinstalling is not sufficient. 

You need to delete all of the elc files wherever ergoemacs-mode is installed restart emacs,  then reinstall.

**Comment by mattfidler** [comment]
I think this is caused by Compiling against an outdated ergoemacs-macros file

**Comment by timseries** [comment]
Hi Matt, I'm still having this issue, even after starting from a fresh, barebones emacs (24.1) installation on OSX. I simply followed the manual install directions [here](https://ergoemacs.github.io/).

The contents of my init.el file are:
```
add-to-list 'load-path "~/.emacs.d/ergoemacs-mode")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)
```

If it helps, CMD-SPC works for set-mark, but C-SPC does not, I still get this:

![image](https://cloud.githubusercontent.com/assets/2424235/13201611/4fd4244c-d82e-11e5-8405-227dff9e9aa7.png)

Also, M-s does not switch to the next pane as I would expect (but M-S does switch to the previous pane).

My ergoemacs path has no *.elc files...
![image](https://cloud.githubusercontent.com/assets/2424235/13201644/939f5510-d82f-11e5-99b0-62f311bc4a10.png)

**Comment by mattfidler** [comment]
What is the value of ergoemacs-dir ?

**Comment by mattfidler** [comment]
Also try pressing ctrl-u ctrl-u Ctrl-h z to recompile everything, or
upgrade your emacs to 24.5

**Comment by timseries** [comment]
Ergoemacs dir is "/Users/tim/.emacs.d/ergoemacs-mode"

I tried the recompile command, same behavior as before. 

I checked again and my Emacs version is 24.5.1.

Just a hunch, do you think think this may be the issue?

https://github.com/ergoemacs/ergoemacs-mode/blob/b18811024ced50f47bbd2bea50470d33d9628dde/ergoemacs-themes.el#L559

**Comment by mattfidler** [comment]
Did you make the change to the key after you load ergoemacs-mode?

**Comment by timseries** [comment]
No, I have a bare Emacs 24.5.1 installation with the init.el file posted above. Typing C-SPC still gives the warning at the bottom
```
^Space is disabled! Use ^@ for set-mark-command
```
M-s still doesn't work either. :-(

Or perhaps I misunderstood your question?

**Comment by mattfidler** [comment]
Your init file says

```lisp
(add-to-list 'load-path "~/.emacs.d/ergoemacs-mode")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)
```

But it should have

```lisp
(add-to-list 'load-path "~/.emacs.d/ergoemacs-mode")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)
(global-set-key (kbd "C-SPC") 'set-mark-command) ;; Change after ergoemacs-mode
```

For some keys you can set them before `ergoemacs-mode` loads.

**Comment by timseries** [comment]
Thanks for the quick reply Matt. I have added this to my init.el and nothing changes. However, if I evaluate 
```
(global-set-key (kbd "C-SPC") 'set-mark-command)
```
after Emacs loads (`eval-region`) then I get the desired behavior.

Wasn't C-SPC always supposed to be set mark? I'm a little confused as to why this would have to be set in my init.el.

So I'm experiencing the same behavior as describe in the first comment of this issue.

**Comment by mattfidler** [comment]
C-SPC was unset a long time ago.  I can now reproduce your issue.  I'm unsure when it started.

**Comment by timseries** [comment]
That's interesting, I haven't updated my Emacs in a while. I think M-s and isearch forward/backward are still problematic (as mentioned by others). I had a look at the git history, you're right in saying C-SPC was unset a long time ago. 

May I ask why the default behavior was changed?

**Comment by mattfidler** [comment]
It was before my time as maintainer. I believe it was changed because <kbd>M</kbd>-<kbd>SPC</kbd> doesn't require the pinky stretch that <kbd>C</kbd>-<kbd>SPC</kbd> requires; you can use your thumb to press the <kbd>M</kbd> key. This pinky stretch is still there even if you remap the caps lock to the control key.

The <kbd>M</kbd>-<kbd>s</kbd> bug was introduced recently,  since it was working recently.

If you are referring to isearch repeating with <kbd>M</kbd>-<kbd>;</kbd> it should work if you select a different version of ergoemacs-mode keybindings. I think that you are looking for version `5.7.5`

That is

```lisp
(add-to-list 'load-path "~/.emacs.d/ergoemacs-mode")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-theme-set-version "5.7.5") ;; Set to old version of keys.
(ergoemacs-mode 1)
(global-set-key (kbd "C-SPC") 'set-mark-command) ;; Change after ergoemacs-mode
```

Note that Xah changed isearch-forward to <kbd>Alt</kbd>+<kbd>y</kbd> because it is heavily used and he believes that since you are using the pointer finger, you are less likely to develop RSI.

**Comment by mattfidler** [comment]
It seems to work.

**Comment by mattfidler** [comment]
You don't have to reset C-SPC if you use the

```lisp
(add-to-list 'load-path "~/.emacs.d/ergoemacs-mode")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-theme-set-version "5.7.5") ;; Set to old version of keys.
(ergoemacs-mode 1)
(global-set-key (kbd "C-SPC") 'set-mark-command) ;; Change after ergoemacs-mode
```

**Comment by timseries** [comment]
Yes, it does. Thanks a bunch for fixing this so quickly and for maintaining this package.

**Comment by mattfidler** [comment]
Great!   Thanks for your patience.
