### ISSUE TITLE
Shell-mode overrides some basic editing/motion commands

### ISSUE THREAD

**Issue by pdg137** [ergoemacs/ergoemacs-mode#400]
Alt+P, Alt+R, and Alt+N do not follow the ErgoEmacs bindings in shell-mode under ergoemacs-mode-20160114.1028; I think at least Alt+R worked about a year ago.  If possible, I think we should retain *all* ErgoEmacs shortcuts in shell-mode by default, so that we don't surprise people.

**Comment by mattfidler** [comment]
I agree.  Could you post your configuration.  I personally cannot reproduce your issues.  I use colemak keyboard layout and reduction theme, and the keys you named work great for me.

**Comment by pdg137** [comment]
Removing pcache AND reinstalling ergoemacs-mode as you suggested in Issue #397 fixed this!
