### ISSUE TITLE
Add equivalent to cua mode option cua-keep-region-after-copy

### ISSUE THREAD

**Issue by Valdaer** [ergoemacs/ergoemacs-mode#401]
Since ergoemacs-mode does not use cua-mode the [cua mode's](http://superuser.com/questions/514480/avoid-unselecting-region-when-copying-text-in-emacs-using-cua-mode)
 option cua-keep-region-after-copy doesn't work.

The functionality of avoiding to unselect a region when copying text would be nice to have to give users a configuration ability to make consistent behavior with other programs(most do keep selection after Ctrl+C).

It should be easy to add, simply add another case to [this function](https://github.com/ergoemacs/ergoemacs-mode/blob/cb79c8a9be92140408ba27454ac00883a1fe1c09/ergoemacs-functions.el#L398) and some configuration variable in ergoemacs-theme? However I'm more or less a beginner in LISP and I don't have time to write it. I would if it could be written in Scala/Java/Python.

**Comment by mattfidler** [comment]
This should work:
```lisp
(setq ergoemacs-keep-region-after-copy t)
```

**Comment by cblp** [comment]
No. `ergoemacs-keep-region-after-copy` does not exist.

**Comment by mattfidler** [comment]
Which version of ergoemacs-mode are you using?

**Comment by cblp** [comment]
ergoemacs-mode-5.14.7.3. My Emacs says it's the latest version.

**Comment by mattfidler** [comment]
Sorry for the delayed reply.  It is the most recent stable version.  To use
the unstable where this is corrected you need to remove excess ergoemacs
and install MELPA unstable.  This allows you to install ergoemacs mode with
the lasted the patches.

**Comment by cblp** [comment]
thanks. I'll wait for a stable version

**Comment by Valdaer** [comment]
Unfortunately it doesn't work but I can't reopen the issue. I too wanted to stay using stable version and haven't checked that before. Actually I'm updating my config because updated Debian(and because of that updated Emacs to version 26) and wanted to try this(tested on other machine, it wasn't working on emacs 24 and ergoemacs from meltpa-stable/elpa too).

I've made a pull request  https://github.com/ergoemacs/ergoemacs-mode/pull/490 with the solution from cua mode, I'm using this code since about a week and it's working fine for me so I hope it can be merged.
