### ISSUE TITLE
How to disable annoying messages “- Label->: xxxxxxx” in minibuffer

### ISSUE THREAD

**Issue by linevich** [ergoemacs/ergoemacs-mode#403]
On each action (opening new buffer, opening packages-list), I have different messages in minibuffer, how to disable it?
![screen1](http://i.stack.imgur.com/WWWT1.png)
![screen2](http://i.stack.imgur.com/JWtao.png)

Bug occurs only with MELPA version, GNU one works normally.

**Comment by mattfidler** [comment]
Thanks.  

There currently isn't one,  but I will add it on Monday

**Comment by mattfidler** [comment]
It should only happen on startup.  If you want to change this behavior you can modify `ergoemacs-message-level`
