### ISSUE TITLE
On Ubuntu, selecting text does not copy PRIMARY clipboard anymore

### ISSUE THREAD

**Issue by gamaralf** [ergoemacs/ergoemacs-mode#405]
The problem: on Ubuntu, after activating ergoemacs-mode (M-x ergoemacs-mode), the automatic copy to PRIMARY after selecting text does not work anymore.

In general, Linux systems has at least 2 usable "clipboards". One of them is "CLIPBOARD", you use ctrl-c/cltr-v (copy and paste) to manipulate it, similar to Windows/Mac.

The other one is called "PRIMARY", and by default, when you select text with the mouse, that text is automatically copied to "PRIMARY" and to paste you use the middle mouse button. This is a very useful feature, I use it all the time.

Using Ubuntu 14.04.3 LTS and Emacs 24.5.1.

**Comment by mattfidler** [comment]
Is this when you select using the mouse? Or you select using the keyboard?

**Comment by gamaralf** [comment]
It is when I select text using the **mouse**.

**Comment by mattfidler** [comment]
What is the value of the variable mouse-drag-copy-region

**Comment by gamaralf** [comment]
I tried setting mouse-drag-copy-region##

**Comment by gamaralf** [comment]
Update: when I open another application (like gnome-terminal or gedit) and, with the mouse, select text from that application, I am able to to use the middle mouse button to paste the text into Emacs.

The opposite is not true, if I select text from Emacs I am not able to paste it into another application.

**Comment by mattfidler** [comment]
You can try the update.  Under windows I can select with the mouse and it copies (when `mouse-drag-copy-region` is `t`

**Comment by mattfidler** [comment]
Did this work for you @gamaralf ?

**Comment by gamaralf** [comment]
@mattfidler , unfortunately it did not work. As soon as I activate ergoemacs-mode, the automatic copy to PRIMARY stops working. :(

**Comment by mattfidler** [comment]
I can't exactly test this, but I think it works now.

I tested this by selecting text in windows, and then calling `(x-get-selection 'PRIMARY)`, which seems to match the value correctly.  Please check if this works for you @gamaralf

**Comment by mattfidler** [comment]
Within windows, I select text, then press the middle mouse button and the region is pasted.

**Comment by mattfidler** [comment]
I finally got xwindows access, and this still doesn't work.

**Comment by mattfidler** [comment]
This should now work since ergoemacs-mode doesn't typically interfere with mouse commands any longer.  If this comes up again, let me know.
