### ISSUE TITLE
Unwanted font is forced for Cyrillic characters

### ISSUE THREAD

**Issue by sg2002** [ergoemacs/ergoemacs-mode#408]
I always use a custom default font. When running the new ergoemacs-mode I've noticed that all of the sudden all Russian symbols that I use are rendered with this font:
-outline-Consolas-normal-normal-normal-mono-13-*-*-*-c-*-iso10646-1
And there's nothing I could do about it. Apart from looking somewhat ugly it also screws up spacing in org-mode clock tables with Cyrillic entries.

After some digging I've found that this because of a package called [unicode-fonts](https://github.com/rolandwalker/unicode-fonts).

There's a custom called ergoemacs-use-unicode-symbols, setting which to nil helped in the end.

Still, I have a couple of concerns about this:
1. I don't think ergoemacs-use-unicode-symbols t is a sane default. It took me quite some time to grasp what's happening. A new user would probably go mad in trying to understand why the font he choose from the menu does not work.
2. Even if you set ergoemacs-use-unicode-symbols to nil, unicode-fonts still gets installed.

**Comment by mattfidler** [comment]
Good points.  I will have to consider recoding this.

The unicode-font package has caching utilites that I use.  Perhaps I should break the dependency entirely.

**Comment by mattfidler** [comment]
For now, the unicode-fonts are not required.  I have put `ergoemacs-use-unicode-symbols` default to `t` still since it doesn't force any fonts to be installed any longer.  Rather, if a character can be displayed by the current fontset, it will display the character...

**Comment by sg2002** [comment]
This got broken again. ergoemacs-use-unicode-symbols nil does not help.

**Comment by mattfidler** [comment]
Should be fixed again.
