### ISSUE TITLE
Org-mode: C-c C-x C-i get's treated as C-c C-x i

### ISSUE THREAD

**Issue by sg2002** [ergoemacs/ergoemacs-mode#409]
Org command org-clock-in that is by default set to C-c C-x C-i get's translated to C-c C-x i which is org-insert-columns-dblock.

**Comment by mattfidler** [comment]
You are pressing C-c C-x C-i?

If I remember correctly C-i is equivalent to tab.   Have you tried C-c C-x
tab?

I did something to distinguish between  C-i and Tab under the GUI,  perhaps
it's misbehaving...

**Comment by mattfidler** [comment]
Also,  could you try menu x i

I don't have computer access today

**Comment by mattfidler** [comment]
For me:
 - C-c C-x TAB works
- Both C-c C-x C-i and menu f x i  inserts org-insert-columns-dblock.

**Comment by mattfidler** [comment]
Should be correct function...

**Comment by mattfidler** [comment]
Let me know if it doesn't work for you.
