### ISSUE TITLE
Org-mode: moving point left and right gets it within folded headings

### ISSUE THREAD

**Issue by sg2002** [ergoemacs/ergoemacs-mode#410]
Let's say we have an org file that looks like this:
```
* Heading A
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
* Heading B
```
If you fold heading A and place cursor at A and start moving right, the cursor would be stuck at the first dot for as many presses as many "a" there are. The same thing would happen if you put cursor at the last dot(or further) and start moving left.

**Comment by mattfidler** [comment]
Still need a unit test, but its fixed right now.
