### ISSUE TITLE
Alt key behavior in windows with AHK

### ISSUE THREAD

**Issue by t-kalinowski** [ergoemacs/ergoemacs-mode#420]
Occasionally while in another program, a bare "Alt" keystroke shifts the focus to the menu bar unexpectedly. Would it be possible to modify the .ahk script to enable rerouting a bare "Alt" keypress to do nothing, and perhaps remap the "shift focus to menubar" command to, perhaps, 
- a bare "apps menu" key press, or perhaps 
- a double-tap of the Alt key,
- the right win key
- or some other keystroke i'm not thinking of? 

Ideally this behavior could be toggled quickly through the GUI.

**Comment by t-kalinowski** [comment]
Also, can you possible provide a hint for how would I go about modifying the behavior of go to next word / previous word? I am observing some different behavior between applications. 
In Rstudio (an IDE for R) using Alt+U and Alt+O to go to previous next word, treats " " (space) as a word, always. So to move the cursor from the start of one word to the start of the next word, it takes two keystrokes. This is different from other programs (e.g., this comment box in chrome) where those keystrokes move the cursor from the beginning of one word to the beginning of the next word. (e.g., one key stroke to move the same cursor distance as it takes 2 in Rstudio.

**Comment by t-kalinowski** [comment]
Related question, as I tinker around with this new set of shortcuts: 

Would it make sense to have alt+shift+[jklioum.]  highlight text the cursor moves past? Setting a mark with alt+space works well, but can be less fluid than just adding a shift press while you're in the middle of moving the cursor with alt+[ijkl]. This would bring the behavior more inline with the way the arrow keys behave. Also, a shift+alt+[ijkl] right now doesn't do anything, as far as I can tell, in AHK.

**Comment by mattfidler** [comment]
I'm unsure what you are referring to with the bare "apps" key.  I think this is already covered:

![image](https://cloud.githubusercontent.com/assets/514778/14958247/6ea688d4-104f-11e6-98c1-b7522def83fb.png)

As far as Rstudio, this is its behavior Control Left and Right arrow.  I agree this is different from most other programs.  It would be a chore to program this behavior to be different.  You would probably have to select and then copy the area and see if it is a space to add another keystroke of Ctrl+left. Another option would be repeating  the word movement in R-studio will start skipping spaces, though the first one would not skip a space.

I agree that alt+shift+ makes sense.  I used it in the `reduction` theme for emacs.  However, I haven't programmed anything in the authotkey script.

**Comment by t-kalinowski** [comment]
Thanks Matt.

Re "bare" Alt key: the solution you suggest remaps the "alt" key to another position on the keyboard. This changes it for ALL commands that make use of the "alt" key, including chords based on the Alt key, as well as the command that is sent when just the alt key is pressed (i.e., a "bare" alt key). 

I'm suggesting that JUST the one command of a "bare" alt key is moved, while the alt command as part of any chords remains the same. Currently on windows, the "bare" alt key shifts focus to the menu bar.

The benefit of remapping the "bare" alt key is that you make the alt key less "hot", so that pressing and releasing the modifier key, will not send any commands to the computer.

**Comment by mattfidler** [comment]
I don't think that autohotkey supports this directly.  The closest thing is to have a timer, like the big space package that was incorporated.  I don't think it will stop the activating the menu, though...  The bigspace didn't always act as I had hoped.

I'm not sure there is a solution.  If you can find one, I would be happy to incorporate it.

**Comment by mattfidler** [comment]
The shift selection and Rstudio issuses may be able to be fixed.

**Comment by xahlee** [comment]
this worked for Windows key. Not sure it does for Alt, maybe try that.

;; disable Win key behavior of popping up the Start Menu, but don't
disable Win+‹key› combination~LWin Up::Return
~RWin Up::Return

**Comment by mattfidler** [comment]
I'm not sure

**Comment by mattfidler** [comment]
For me, the ALT key remaps are no longer working correctly with the ergoemacs-mode autohotkey script.  I'm unsure why.

However, running an additional autohotkey script seems to fix the problem.

**Comment by t-kalinowski** [comment]
I've moved away from the ergoemacs mode keys at the time being because I was getting confused between vim hkkl and  ergoemacs arrows ijkl. 

This been working pretty reliably for me:
```
!k::
Send {Up}
Return

!h::
Send {Left}
Return

!j::
Send {Down}
Return

!l::
Send {Right}
Return

!g::
Send {home}
Return

!`;::
Send {end}
Return


; shift to enable highlight
+!k::
Send {Shift Down}{Up}{Shift Up}
Return

+!h::
Send {Shift Down}{Left}{Shift Up}
Return

+!j::
Send {Shift Down}{Down}{Shift Up}
Return

+!l::
Send {Shift Down}{Right}{Shift Up}
Return



; ctrl to enable navigation by whole words
^!k::
Send {Ctrl Down}{Up}{Ctrl Up}
Return

^!h::
Send {Ctrl Down}{Left}{Ctrl Up}
Return

^!j::
Send {Ctrl Down}{Down}{Ctrl Up}
Return

^!l::
Send {Ctrl Down}{Right}{Ctrl Up}
Return


; ctrl + shift to highlight whole words
; ctrl to enable navigation by whole words
+^!k::
Send {Ctrl Down}{Shift Down}{Up}{Shift Up}{Ctrl Up}
Return

+^!h::
Send {Ctrl Down}{Shift Down}{Left}{Shift Up}{Ctrl Up}
Return

+^!j::
Send {Ctrl Down}{Shift Down}{Down}{Shift Up}{Ctrl Up}
Return

+^!l::
Send {Ctrl Down}{Shift Down}{Right}{Shift Up}{Ctrl Up}
Return
```

**Comment by mattfidler** [comment]
Great.   I'm glad it works for you
