### ISSUE TITLE
Space does not get inserted after certain characters

### ISSUE THREAD

**Issue by sg2002** [ergoemacs/ergoemacs-mode#422]
When I type "? " I get a bell ring and space does not get inserted. Happens from clean configuration. This only happens when I type space quickly enough. If I wait a second, it gets inserted.

Now, if my config contains this:

```
(require 'outshine)
(add-hook 'outline-minor-mode-hook 'outshine-hook-function)
(add-hook 'emacs-lisp-mode-hook 'outline-minor-mode)
(setq outshine-use-speed-commands t)
```

I get an error `(wrong-type-argument characterp 33554464)` instead of just the ring.

I've uploaded two backtraces [here](https://www.dropbox.com/s/5rle6zuqtiitfch/backtraces.zip?dl=0), since they contain unprintable characters.

Same thing happens for ", ", but only in russian layout, where it's actually at the same position as "?" in qwerty.

**Comment by mattfidler** [comment]
Sorry this fell off my radar.  I've been a bit busy.  I will try to look into it soon.

**Comment by sg2002** [comment]
No problem, you've already been doing a lot.

**Comment by mattfidler** [comment]
I think this is similar to #375, which seems to be fixed.  Let me know if it doesn't work for you.
