### ISSUE TITLE
Generating keymap cheat sheet fails on OSX

### ISSUE THREAD

**Issue by kevinj2016** [ergoemacs/ergoemacs-mode#425]
Hi, I used the Ergo Emacs menu on my imac OSX machine (emacs 24.4 osx app), and got the following error message in the Async Shell Command buffer. Hope this helps... :-)

Loading ergoemacs-layouts...
Loading ergoemacs-theme-engine...
Loading ergoemacs-themes...
Loading ergoemacs-unbind...
Loading ergoemacs-modal...
Loading ergoemacs-functions...
Loading ergoemacs-translate...
Loading ergoemacs-shortcuts...
Loading ergoemacs-extras...
Loading ergoemacs-advices...
Wrong number of arguments: (0 . 0), 1

**Comment by eva7sk** [comment]
Also Fails On Linux Emacs 24.5 + ErgoEmacs melpa Stable
