### ISSUE TITLE
assignment to free variable ‘ergoemacs-read-from-minibuffer-map’

### ISSUE THREAD

**Issue by Foxly1990** [ergoemacs/ergoemacs-mode#428]
Hi! I'm update my emacs to v25.1.1
After this when i start emacs get warning:
`Warning (bytecomp): assignment to free variable ‘ergoemacs-read-from-minibuffer-map’ [3 times]`
I try to define variable before requires of ergoemacs, but this is doesn't work. Sorry for bad english. I hope you're understand me.

**Comment by mattfidler** [comment]
Can you remove ergoemacs mode restart emacs and then reinstall ergoemacs.  Let me know if that works for you

**Comment by Foxly1990** [comment]
I'm install [ergoemacs-mode 20160926.919] from melpa. And this bug exist

**Comment by mattfidler** [comment]
This seems to suppress the warning for me.  In theory, I should just be able to add

```lisp
(defvar ergoemacs-read-from-minibuffer-map)
```

in the same file, or like you, define it before ergoemacs-mode loads.  However, this seems to suppress the message  for me.

**Comment by Foxly1990** [comment]
![2016-10-05 21-17-31](https://cloud.githubusercontent.com/assets/11314318/19125835/9aee89c6-8b49-11e6-91de-bd4a9627cb42.png)
This is doesn't helped :(

**Comment by Foxly1990** [comment]
Which file in ergoemacs packages need to define "ergoemacs-read-from-minibuffer-map"?

**Comment by mattfidler** [comment]
Did you update the package?

**Comment by Foxly1990** [comment]
Yes! And this warning is gone. Thank you for help!
