### ISSUE TITLE
on melpa, says no description available

### ISSUE THREAD

**Issue by xahlee** [ergoemacs/ergoemacs-mode#429]
on melpa, says no description available

goto
https://melpa.org/

type ergoemacs in the search box. Result will show, and in the description, it says “No description available.”

also critical is that, on twitter, melpa account tweets every update. When it's ergoemacs, it says “No description available.”, looks bad. It's been like that for a while, manybe half a year or more.

I haven't looked into tech detail what caused this. (something about melpa receipe am sure)

I'd like to submit a short description. Something like this:

An efficient keybinding set based on statistics of command frequency, and supports common Windows shortcuts such as Open, Close, Copy, Cut, Paste, Undo, Redo.

For detail, see http://ergoemacs.github.io/

**Comment by mattfidler** [comment]
melpa.org is often firewalled for me.  Could you check to see if this fixed it.  If not, can you look into this @xahlee

**Comment by xahlee** [comment]
![ergoemacs melpa 2016-10-12](https://cloud.githubusercontent.com/assets/404678/19330220/ff59fa9c-9091-11e6-9ae2-1f10f275ce18.png)

doesn't seem fixed

**Comment by xahlee** [comment]
![xx ergoemacs](https://cloud.githubusercontent.com/assets/404678/19330892/052e3e7a-9096-11e6-9095-370393180b18.png)

screenshot from tweeter. This look bad, and make it hard to retweet.

**Comment by mattfidler** [comment]
It should just work.  I have read the documentation on the recipe format and it doesn't specify anything above what is needed for the package for elpa.

**Comment by syohex** [comment]
https://github.com/ergoemacs/ergoemacs-mode/pull/433

Because package format is not correct.

**Comment by mattfidler** [comment]
Should be fixed.  Thanks @syohex
