### ISSUE TITLE
Problem opening files with helm

### ISSUE THREAD

**Issue by CallumCameron** [ergoemacs/ergoemacs-mode#436]
Using the latest helm and ergoemacs-mode from Melpa Stable on Emacs 25.1, I get an error when trying to open any files through C-o: 'void variable helm-follow-mode'. Example .emacs:

    (require 'package)
    (setq
     package-enable-at-startup nil
     package-archives '(("melpa-stable" . "https://stable.melpa.org/packages/")
                        ("melpa" . "https://melpa.org/packages/")
                        ("gnu" . "https://elpa.gnu.org/packages/")))

    (package-initialize)

    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))

    (require 'use-package)

    (setq use-package-always-ensure t)

    (use-package ergoemacs-mode
      :pin melpa-stable
      :config
      (ergoemacs-mode))

    (use-package helm
      :pin melpa-stable
      :config
      (require 'helm-config)
      (helm-mode 1))

    (setq debug-on-error t)

Adding `(setq helm-follow-mode nil)` as a workaround lets me open files again. I had the same problem with the old stable ergoemacs on Emacs 24.5 after upgrading helm a few days ago, so I suspect something has changed there.

**Comment by mattfidler** [comment]
Thanks for the bug report.  I have added a work-around.  It should work without using the `(setq helm-follow-mode nil)`

If you have any problems let me know.

**Comment by CallumCameron** [comment]
It works, thanks.
