### ISSUE TITLE
Multilingual input methods don't work 2

### ISSUE THREAD

**Issue by m00natic** [ergoemacs/ergoemacs-mode#439]
Similar to #352 but this time the other way around:

M-x ergoemacs-clean

Command
"/usr/bin/emacs" --debug-init -Q -L "/home/censored/.emacs.d/elpa/ergoemacs-mode-20161025.1222/"  --load="ergoemacs-mode" --load="ergoemacs-test"  --eval "(progn (require 'elp) (setq debug-on-error t) (elp-instrument-package (symbol-name 'ergoemacs-)) (ergoemacs-mode 1) (run-with-idle-timer 0.1 nil 'elp-results))"

...

Loading /home/censored/.emacs.d/elpa/ergoemacs-mode-20161025.1222/ergoemacs-global-25-1-1-x86-64-unknown-linux-gnu.el.gz...
uncompressing ergoemacs-global-25-1-1-x86-64-unknown-linux-gnu.el.gz...done
Loading /home/censored/.emacs.d/elpa/ergoemacs-mode-20161025.1222/ergoemacs-global-25-1-1-x86-64-unknown-linux-gnu.el.gz...done
Breadcrumb -2305843009213693944
Ergoemacs will be started.
Function icicle-repeat-complex-command is already compiled
Loading /home/censored/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Ergoemacs-mode turned ON (colemak:standard).
Started ‘ergoemacs-mode’. Total startup time 3.480871 (Load: 1.507124, Initialize:1.973747)

M-r (to go to the *scratch* buffer)
C-\ (change to alternative input method, see the old ticket)

Now try to use ergoemacs move or whatever M bindings:

M-i
M-k

Then don't work and instead insert something like (might be dependent
on the input language and/or layout, this is with default-input-method
"bulgarian-phonetic" and colemak ergoemacs layout):

õå

**Comment by mattfidler** [comment]
I'm not sure if this will fix the issue for you, but I think it might.  I removed some of the internal handling of keystrokes.  I have some problems testing this.

**Comment by m00natic** [comment]
Seems to work fine now.  It even fixes #375!

Well done!

**Comment by mattfidler** [comment]
Thanks.  It seems to be more responsive for me too.
