### ISSUE TITLE
ErgoEmacs 25.1.1 crash when resize buffer (enlarge-window)

### ISSUE THREAD

**Issue by alexei28** [ergoemacs/ergoemacs-mode#440]
Windows 7 (64 bit), Emacs 25.1.1. , package "ergoemacs-mode".
Split any buffer. Then when I try to resize buffer (enlarge-window) BY MOUSE I get the next message (in Message buffer):

Warning (ergoemacs): Increased max-specpdl-size to 2600 and max-lisp-eval-depth to 1600 for (lambda nil (interactive) nil (mouse-drag-mode-line last-command-event) (ergoemacs-command-loop--execute-modify-command-list (quote mouse-drag-mode-line)))

And when try again to resize buffer then Emacs is crash!
When I do same in pure emacs 25.1.1 - no problem.

**Comment by mattfidler** [comment]
This works for me.  It seems like a duplicate bug report.
