### ISSUE TITLE
Emacs 25.1 - package "ergoemacs-mode" : Warning (ergoemacs): Increased max-specpdl-size to...

### ISSUE THREAD

**Issue by alexei28** [ergoemacs/ergoemacs-mode#442]
Windows 7 (64 bit)
Emacs 25.1
install package "ergoemacs-mode" from "melpa" repo
1. Split vertically any buffer by Alt-4
2. Try to move up statusbar BY MOUSE
3. As result get error (in *Warning* buffer):

**Warning (ergoemacs): Increased max-specpdl-size to 5200 and max-lisp-eval-depth to 3200 for (lambda nil (interactive) nil (mouse-drag-mode-line last-command-event) (ergoemacs-command-loop--execute-modify-command-list (quote mouse-drag-mode-line)))**

4. And I try again to move up , the Emacs is CRASH

**Comment by mattfidler** [comment]
This works for me.  It took me awhile to track this down.  Hopefully it works for you.  Let me know if it doesn't.
