### ISSUE TITLE
Ctrl+c Ctrl+x doesn't work

### ISSUE THREAD

**Issue by P4bl000** [ergoemacs/ergoemacs-mode#444]
Hello. After update emacs to 25.1.1 version, i see this problem. Copy/cut work on alt+c/alt+x shortcuts. After press ctrl+c/ctrl+x nothin's happen. I set ergoemacs-ctl-c-or-ctl-x-delay to 1, but no result. If i try to set timeout through menu i have this message.
`Wrong number of arguments: (2 . 2), 1`

**Comment by mattfidler** [comment]
This is a partial fix.  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd> does not activate the C-c menu when something is selected.  Instead it only activates copy.  The same is true for C-x.

**Comment by P4bl000** [comment]
And how ia can use standart `C-c <ergoemacs-timeout>` shortcut? This is one of the main reasons that i install ergoemacs. Comfort hotkeys.

**Comment by mattfidler** [comment]
If you update the ergoemacs-mode, you should be able to use the standard shortcuts:

https://ergoemacs.github.io/cua-conflict.html

For some reason the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd> doesn't yet work.

**Comment by mattfidler** [comment]
The <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd> and The <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>x</kbd> keyboard shortcuts work as advertised again.  Let me know if this is true for you, if you have time.
