### ISSUE TITLE
Package company-mode not work with ergoemacs

### ISSUE THREAD

**Issue by alexei28** [ergoemacs/ergoemacs-mode#447]
Windows 7 (64 bit)
Emacs ver. 24.5, package "ergoemacs".
My init.el file:

**;;Install ergoemacs-mode from "melpa" repo
(add-to-list 'load-path "~/.emacs.d/elpa/ergoemacs-mode-20161025.1222/")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)**

Also I success installed package "company" from Elpa repo by list-package:
_https://github.com/company-mode/company-mode_
And this package not work.
But if I uninstall package "**ergoemacs**" and restart Emacs then package "company-mode" success work!

**Comment by mattfidler** [comment]
I will look into this soon.

**Comment by mattfidler** [comment]
I cannot reproduce your issue.  Company mode works for me.

**Comment by mattfidler** [comment]
Could you update your ergoemacs-mode;  Perhaps that is the issue?

**Comment by dgutov** [comment]
Yeah, it's been fixed in company-mode master. Thanks!

**Comment by mattfidler** [comment]
Great, thanks!
