### ISSUE TITLE
Issues #442 and #440 (macOS version)

### ISSUE THREAD

**Issue by tomfloyer** [ergoemacs/ergoemacs-mode#448]
macOS Sierra (10.12.3)
Emacs 25.1 (tried both from brew and https://emacsformacosx.com)
Ergomacs from melpa-stable

As I mentioned in title, I have the same issues when resizing buffer after split (as in  #442 and #440 ). 
After resizing I get this warning:
`Warning (ergoemacs): Increased max-specpdl-size to 2600 and max-lisp-eval-depth to 1600 for (lambda nil (interactive) nil (mouse-drag-mode-line last-command-event) (ergoemacs-command-loop--execute-modify-command-list (quote mouse-drag-mode-line)))`

After that, I'm not able to resize buffer anymore.

P.S. I wish I could fix it by myself, but I'm just a newbie.

**Comment by mattfidler** [comment]
What version of ergoemacs-mode are you using.  I think I may have already resolved it, but I'm unsure if I made it stable or not.

**Comment by tomfloyer** [comment]
5.16.10.12
I use stable version, cause I experienced more bugs in non-stable version

**Comment by mattfidler** [comment]
I think this was fixed in the unstable version, but as you noted there are bugs that hasn't been fixed there.  Could you check the unstable to see if this bug was fixed...?  I will concentrate on getting the unstable to a stable state and then marking it stable again.

**Comment by tomfloyer** [comment]
I've checked everything again, this bug doesn't appear in unstable version anymore. I've definitely messed up with the `init.el`

**Comment by mattfidler** [comment]
Thank you for getting back to me.  I will look into some of the unstabilities in the current unstable to push out a new version soon, if I can get some time.
