### ISSUE TITLE
Installation without ELPA without Internet access takes >60s to start

### ISSUE THREAD

**Issue by rschmidlin** [ergoemacs/ergoemacs-mode#449]
By cloning the repository, extending the load-path and requiring ergoemacs-mode, Emacs takes up to a minute to start on absence of Internet because ELPA tries to update undo-tree and persistent-soft on each start. 

Actually I also had to connect the computer to the internet to initially install the required packages because ErgoEmacs wouldn't accept the manually installed ones. Is there a way of configuring ErgoEmacs to not use ELPA for computers without continuous access to the Internet?

**Comment by mattfidler** [comment]
This needs to be fixed.  I will look into this soon.

**Comment by mattfidler** [comment]
Do you have undo-tree and persistent soft already installed?

**Comment by mattfidler** [comment]
It shouldn't require them any longer.  

I looked through the code, and I think that ergoemacs-mode can function without them.
