### ISSUE TITLE
Symbol's function definition is void: ergoemacs-where-is-old-binding

### ISSUE THREAD

**Issue by idavydov** [ergoemacs/ergoemacs-mode#451]
Hi,
I'm using emacs 24.5.1 and ergoemacs-mode 20170321.1249 from melpa.
When I press "Ctrl+H O", I get:
```
Symbol's function definition is void: ergoemacs-where-is-old-binding
```

**Comment by mattfidler** [comment]
You are right; The function somehow disappeared.

**Comment by mattfidler** [comment]
This seems to work for me.  Let me know if it works for you.
