### ISSUE TITLE
ErgoEmacs is broken on NixOS

### ISSUE THREAD

**Issue by gnidorah** [ergoemacs/ergoemacs-mode#452]
Hi.
It worked fine in the past, but starting from some newer version few things gone wild:

1. On a first start, `mkdir ~/.emacs.d/ergoemacs-extras` is needed, otherwise Emacs will hang
2. When ErgoEmacs is enabled, Emacs launch time is much longer, in the status bar I see that for some reason it also begins to look through elpa, melpa etc sites. Is it possible to disable this new behaviour via config? In NixOS, it's up to the package manager to deal with Emacs packages, it's not ErgoEmacs business :-)

Could you please fix these things?
Thanks.

**Comment by mattfidler** [comment]
I'm unsure why you need to make the directory ~/.emacs.d/ergoemacs-extras;  In theory ergoemacs-mode should make this for you...  Is this directory not writable by emacs in NixOS?

As far as removing ergoemacs-mode dependence on package managers, I think it needs to stop checking the packages as it boots up.

**Comment by gnidorah** [comment]
@mattfidler 
> I'm unsure why you need to make the directory ~/.emacs.d/ergoemacs-extras; In theory ergoemacs-mode should make this for you... Is this directory not writable by emacs in NixOS?

No, NixOS doesn't touch home directory. So by some reason `ergoemacs-mode` doesn't create `~/.emacs.d/ergoemacs-extras`.  Some NixOS contributor blamed `ergoemacs-mode` for that and suggested to report this issue upstream, so that's why I'm writing about it: https://github.com/NixOS/nixpkgs/issues/24540#issuecomment-290985904

There was no such issue in the past. If I create that directory manually, everything is fine. Here's the Messages from Emacs when this issue happens:
```
Loading ergoemacs-macros...
Loading two-column...
Loading ergoemacs-themes...
Warning (ergoemacs): Could not find global map information
global-map-list nil
minibuffer-local-map (minibuffer-local-map)
European: (describe-european-environment-map)
Completed generating default keys file.
compressing ergoemacs-global-25-1-1-x86-64-unknown-linux-gnu.el.gz...
Loading /home/gnidorah/.emacs.d/recentf...
Cleaning up the recentf list...
Cleaning up the recentf list...done (0 removed)
Ergoemacs-mode turned ON (us:standard).
Started ‘ergoemacs-mode’. Total startup time 3.282957 (Load: 2.444770, Initialize:0.838187)
Opening output file: No such file or directory, /home/gnidorah/.emacs.d/ergoemacs-extras/ergoemacs-global-25-1-1-x86-64-unknown-linux-gnu.el.gz
<HANG>
```

**Comment by mattfidler** [comment]
This should be fixed.  Let me know.

**Comment by gnidorah** [comment]
@mattfidler Got fixed. Thank you much!
