### ISSUE TITLE
Possible to make ergoemacs do not force user to fetch other packages?

### ISSUE THREAD

**Issue by abelardojarab** [ergoemacs/ergoemacs-mode#454]
I used to love ergoemacs; but there are some features I do not agree very much (no intention to offend at all).

1. If I control the status of my emacs packages by my self (using use-package; in addition to my own repositories forked from those packages); can I disable ergoemacs to try to connect to melpa? i find that behavior intrusive and does not work well if i already have those packages installed; also doesnt work well if I dont have internet connection.

2. I was able to add code into ergoemacs to disable connection to melpa (i have not made a pull request into this git repository though, yet) but I still see that there are several add-hook that are added into the eval-expression and the emacs load-theme. Is it possible to disable the hooks on load-theme

i have my repository here (thanks again for the understanding; i work for Intel in Linux driver development so I will be glad to help and contribute code if you would like too :)) bests there
Abelardo

https://github.com/abelardojarab/emacs-config

**Comment by abelardojarab** [comment]
the ergoemacs mode i have i posted in my markdown readme was
Fixed ergoemacs-mode, such that it does not invoke (package-initialize) in case there is no Internet connection

but truly i should not say 'fixed it' but changed code to not invoke package initialize. so i was able to disable the package initialize; but the hooks remain and when i try to change theme i keep getting 'exceeded maximum stack depth'....

i would love to start using ergoemacs again; could you please provide workaround. thanks for understanding.

**Comment by mattfidler** [comment]
I thought I fixed that here: 7df155e52c86e1db5e69c16830643adfdf7cd1a8

**Comment by mattfidler** [comment]
I don't think `package-initialize` causes the download from melpa, but rather the `package-refresh-contents`

**Comment by mattfidler** [comment]
I'm a bit confused about what you are after for your item 2.  Do you mean suppress all ergoemacs-mode hooks while running the load-theme?

**Comment by abelardojarab** [comment]
Hi Matt
I hope you are well. the situation is i download ergoemacs-mode as one of my subdirectories inside .emacs.d/

i loaded ergoemacs mode and after i run "helm-themes"; which I got from here
https://github.com/syohex/emacs-helm-themes

just invoking 'helm-themes' after loading ergoemacs-mode completely freezes emacs. Ctrl-g does not work and I have to kill emacs. I am using emacs 25.1

**Comment by mattfidler** [comment]
I tried to reproduce this and I could not.

**Comment by abelardojarab** [comment]
Hi Matt

First thanks a lot for the help. I use Emacs for C/C++ driver development for FPGA accelerators.

My repository is here:
https://github.com/abelardojarab/emacs-config

i have a .emacs and .emacs.d inside. I create symbolic links to .emacs file and .emacs.d at the root of my home directory (i.e. $HOME or ~/ )

I used git subtree to fetch ergoemacs repository. 

After Emacs finishes startup sequence and without loading ergoemacs-mode yet; if you input M-x helm-themes you will see that you can switch themes normally. I added defadvice to change the fringe color and the tabbar colorset and the powerline colorset when a new theme is loaded; as I was dissapointed that load-theme didnt adjust neither fringe, tabbar and powerline colorsets.

So you will see that M-x helm-themes will work well without ergoemacs-mode

but after loading ergoemacs-mode

a. M-x helm-themes will freeze Emacs completely
b. months ago if i run helm-themes after loading ergoemacs-mode and disabling package-related functions inside Ergoemacs codebase Emacs would not hang but would helm-themes would give an error of maximum stack depth reached; but this was months ago; now invoking M-x helm-themes just freezes Emacs

could you please give me a hand with this? i would love to start using Ergoemacs mode again.

**Comment by mattfidler** [comment]
Done
