### ISSUE TITLE
Problem with arrow keys on OS X and emacs 25.2.1

### ISSUE THREAD

**Issue by samdmarshall** [ergoemacs/ergoemacs-mode#458]
Hi, i love the sets of single-key shortcuts that this package provides; but i'm having a problem with usage of the arrow keys. This seems to be a recurring issue with the arrow keys inserting `A`, `B`, `C`, and `D` for the `[(up)]`, `[(down)]`, `[(right)]`, and `[(left)]` keys respectively. This is on a fresh install of ergoemacs off of the master branch, and using emacs 25.2.1 on OS X. I've attempted remapping the arrow keys after the ergoemacs package gets loaded and that seems to make no difference. I don't have this problem when not loading the ergoemacs package though. Unlike some other cases of this problem i am running emacs locally (not over putty).

**Comment by mattfidler** [comment]
However, you are likely running this is iTerm.  These are typically
terminal issues.  Am I correct?

**Comment by samdmarshall** [comment]
No, I am running this in Terminal.app, not iTerm.

**Comment by mattfidler** [comment]
This happens no matter the terminal emulator, Putty iTerm etc.  I will have
to look into it later.

**Comment by samdmarshall** [comment]
In the interim could you tell me how to disable the remapping of the arrow keys by ergoemacs please?

**Comment by mattfidler** [comment]
You need to disable the Alt O key

**Comment by samdmarshall** [comment]
that worked perfectly, thanks so much.

**Comment by CallumCameron** [comment]
I have the same problem (on Linux, in Gnome Terminal), but unbinding Alt O didn't work; after `(global-unset-key (kbd "M-o"))` I get 'Alt+O does not do anything!', as expected, but the arrow keys still insert A, B, C, and D.

This looks like escape sequences being handled incorrectly. The letters inserted are the last character of the escape sequences for the arrow keys: ^[0A, ^[0B, ^[0C and ^[0D. The same thing happens with Home and End, which in Gnome Terminal have escape sequences ^[0H and ^[0F. However, on the Linux virtual console where the escape sequences are ^[[1~ and ^[[4~, Home and End work, but the arrow keys (which are the same as in Gnome Terminal) still don't.
