### ISSUE TITLE
Emacs 25.2 and help key

### ISSUE THREAD

**Issue by am6422** [ergoemacs/ergoemacs-mode#459]
Using Ubuntu 16.04, Emacs 25.2 (compiled from scratch) and ergoemacs (from packages) 5.16.10.12

Ctrl-H + K do not work ....same by using Ctrl-H + 3

Emacs message log

ergoemacs-command-loop--grow-interactive: Args out of range: "", -1

Tested on emacs 25.2 with NO other packages (only ergoemacs) and dependencies as installed by package install

elpa

ergoemacs-mode-5.16.10.12
gnupg
list-utils-20160414.702
ls.txt
pcache-20170105.1414
persistent-soft-20150223.1053
undo-tree-0.6.5
undo-tree-0.6.5.signed

**Comment by am6422** [comment]
Follow also procedures as described by the blog 
emacs -Q
(setq debug-on-error t) ; Activate debugging
(add-to-list 'load-path "~/.emacs.d.test/elpa/ergoemacs-mode-5.16.10.12")
(require 'ergoemacs-mode)
(setq ergoemacs-debug t)
(setq ergoemacs-keyboard-layout "us") ; Layout you use.
(setq ergoemacs-theme nil) ; For standard theme.
(ergoemacs-mode 1)

Same result see mesg Log
ergoemacs-command-loop--grow-interactive: Args out of range: "", -1

**Comment by mattfidler** [comment]
Sorry for the late reply.  Have you tried the unstable version.  I think this works there.

**Comment by am6422** [comment]
Yes it does...

**Comment by mattfidler** [comment]
I will work to correct the failing tests and release a new stable release to fix this problem then.
