### ISSUE TITLE
Opening print interface and closing it causes the path in file dialogs to be italicized

### ISSUE THREAD

**Issue by ceridwen** [ergoemacs/ergoemacs-mode#461]
Hitting Ctrl-p or any other shortcut key to open the printing interface for a buffer, then closing it with Ctrl-w or a  similar command will cause the text in the mini-buffer (to open a file, to select a file with M-x recover-file) to be italicized until you close the original buffer.

**Comment by mattfidler** [comment]
Reopen if you have issues on the new github version
