### ISSUE TITLE
JP English/Romaji QWERTY Mac Keyboard Layout

### ISSUE THREAD

**Issue by zenshinji** [ergoemacs/ergoemacs-mode#462]
Hi, All!

Love the work! Here is a layout for a Japanese Mac (specifically early 2015 MacBook Air) keyboard in English/Romaji layout:

`(defvar ergoemacs-layout-jp-mac-en
  '("" "" "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" "-" "^" "¥"
    "" ""  "q" "w" "e" "r" "t" "y" "u" "i" "o" "p" "@" "[" ""
    "" ""  "a" "s" "d" "f" "g" "h" "j" "k" "l" ";" ":" "]" ""
    "" ""  "z" "x" "c" "v" "b" "n" "m" "," "." "/" "_" "" ""
    ;; Shifted
    "" "" "!" "\"" "#" "$" "%" "&" "\'" "(" ")" "0" "=" "~" "|"
    "" ""  "Q" "W" "E" "R" "T" "Y" "U" "I" "O" "P" "`" "{" ""
    "" ""  "A" "S" "D" "F" "G" "H" "J" "K" "L" "+" "*" "}" ""
    "" ""  "Z" "X" "C" "V" "B" "N" "M" "<" ">" "?" "_" "" "")
  "JP English/Romaji QWERTY Mac Keyboard")`

Note that 0 (zero) and _ (underscore) keys are the same shifted and unshifted on this keyboard. Also, there is no "native" \ (backslash).

Let me know if you have any questions.

**Comment by mattfidler** [comment]
Thank you for the layout!
