### ISSUE TITLE
ergoemacs-map-properties--key-struct: Wrong type argument: char-or-string-p, nil

### ISSUE THREAD

**Issue by zenshinji** [ergoemacs/ergoemacs-mode#463]
I get the following error when I enable ergoemacs mode:

>ergoemacs-map-properties--key-struct: Wrong type argument: char-or-string-p, nil

I attached the backtrace.
[Backtrace.txt](https://github.com/ergoemacs/ergoemacs-mode/files/1144772/Backtrace.txt)

ergoemacs-mode-20170509.1202
GNU Emacs 25.2.1 on macOS, built from MacPorts

Let me know if you have any questions.

Thank you!

**Comment by mattfidler** [comment]
Does this only occur when hydra is enabled?

**Comment by luposlip** [comment]
I get that also, any updates?

**Comment by mattfidler** [comment]
No.  Do you have a reproducible example?

**Comment by mattfidler** [comment]
Reopen if you have issues on the new github version
