### ISSUE TITLE
C-h f doesn't work with lvl1 theme: Wrong type argument: integer-or-marker-p, nil

### ISSUE THREAD

**Issue by philip-bl** [ergoemacs/ergoemacs-mode#466]
I started emacs with `emacs -Q`. I pasted the following in *scratch* buffer:

```lisp
(setq debug-on-error t) ; Activate debugging
(add-to-list 'load-path "~/.emacs.d/elpa/ergoemacs-mode-5.14.7.3")
(require 'ergoemacs-mode)
(setq ergoemacs-debug t)
(setq ergoemacs-theme "lvl1")
(setq ergoemacs-keyboard-layout "us")
(ergoemacs-mode 1)
```

I did `M-x eval-buffer`. I pressed `C-h f setq RET` and got `Wrong type argument: integer-or-marker-p, nil` in minibuffer instead of help.

I have GNU Emacs 25.1.1

**Comment by philip-bl** [comment]
Nevermind. I upgraded *ergoemacs-mode`, and it works now.

**Comment by mattfidler** [comment]
that happens sometimes when upgrading emacs.  You bed to upgrade everything.
