### ISSUE TITLE
Alt+RET in org-mode doesn't continue list

### ISSUE THREAD

**Issue by anbasile** [ergoemacs/ergoemacs-mode#470]
In org-mode 9.1.2, using last version of ErgoEmacs, if I type this:

    1. item
And then I hit Alt+RET to have continue the list:

    1. item
    2.

I get the cursor in the correct position but no number inserted:

    1. item
       # cursors ends here

The same for plain lists. Instead, check boxes (Alt+Shift+RET) work fine:

      - [ X ] this
      - [ X ] works

I tried this with a clean configuration, using only org-mode and ergoemacs (from git) installed.

**Comment by mattfidler** [comment]
I just installed org from the elpa mirror and I couldn't reproduce your issue :(

I'm sorry.  I can't figure it out.

**Comment by anbasile** [comment]
This is the init that I am using to debug this:
```
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'package)

(add-to-list 'load-path "~/.emacs.d/ergoemacs-mode")
(require 'ergoemacs-mode)

(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (org org-plus-contrib))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "it") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)

```

I also tried to set the laybout to 'us' but it didn't change anything. I am desperate: my whole workday relies on ergoemacs, org-mode and lists.

**Comment by anbasile** [comment]
UPDATE: I've found that this works:


```
(add-hook 'org-mode-hook
	  (lambda ()
	    (define-key org-mode-map (kbd "<M-RET>")
	      'org-insert-item)))
```

Are there any prolems in using this on the long run? Can I trust this solution?

**Comment by mattfidler** [comment]
Your solution should work.  I don't know if it will causue problems in the long run, though I doubt that it will.

However, if you are having this issue, others are probably having it too (even though I cannot reproduce it personally).    I have added into ergoemacs-mode, just in case.

**Comment by mattfidler** [comment]
If you update and it works for you, let me know and you or I can close the issue.

**Comment by anbasile** [comment]
It works fine for inserting items, but I noticed something else: I can't move items (both lists and trees) up and down.

**Comment by mattfidler** [comment]
I'm confused by your statement.  I don't think you should be able to move items with the alt+RET

**Comment by anbasile** [comment]
No, I should move them with Alt+Up/Down but I can't.

**Comment by anbasile** [comment]
UPDATE: I just updated everything (org and ergoemacs) to last version and now everythings is working fine. You can close this issue. Thanks.

**Comment by mattfidler** [comment]
Thanks.  I'm unsure why it wasn't working before...
