### ISSUE TITLE
Disabling the SPC binding in minibuffer

### ISSUE THREAD

**Issue by xsrvmy** [ergoemacs/ergoemacs-mode#471]
ErgoEmacs appears to add a really annoying space key binding in the minibuffer, so a literal space in a filename has to be entered via Ctrl-Q Space. Is there a toggle to disable that? (I'm new to emacs.)

**Comment by mattfidler** [comment]
I do not have that issue.  With emacs and ergoemacs enabled I can insert a
space with space when opening a file.  If you use something like ido or
helm, this is not the case.

**Comment by xsrvmy** [comment]
Here is the beginning of the output of Ctrl-H K SPC in the minibuffer:

SPC runs the command minibuffer-complete-word (found in
ergoemacs--original-local-map), which is an interactive compiled Lisp
function in ‘minibuffer.el’.

It would appear that ergoemacs is the cause of the issue here.

**Comment by mattfidler** [comment]
No.  The original local map is a copy of the original emacs keybindings.  I
believe that emacs itself binds space.  In theory, space should be the
right binding in certain circumstances.

If this is the case, you can see which keymaps bind space in minibuffer and
then undefined them.

**Comment by mattfidler** [comment]
The space binding is described here

https://www.gnu.org/software/emacs/manual/html_node/emacs/Completion-Commands.html#Completion-Commands

**Comment by mattfidler** [comment]
If you are indeed completing file names, please give a bit more information, like emacs version, ergoemacs version, platform, so I might be able to reproduce it.

**Comment by wlandry** [comment]
I can see this same problem, where SPC is completing in the minibuffer.  

I am running Emacs 26.1 on Debian buster.  Starting emacs with  `emacs -Q` and then running `find-file`, I do not get SPC completing.  Evaluating the following in `*scratch*`

```
(add-to-list 'load-path "/home/boo/ergoemacs-mode/")
(require 'ergoemacs-mode)

(setq ergoemacs-theme nil)
(setq ergoemacs-keyboard-layout "us")
(ergoemacs-mode 1)
```
where /home/boo/ergoemacs-mode has the current version in git 
```
8a65bf2ffb4698f1848070cc84ecaf87d891d850
```
I get the erroneous SPC completion in the minibuffer.  Otherwise, ergoemacs seems to be working.

**Comment by wlandry** [comment]
I also see this behavior with Emacs 27 on a Mac using the latest version from melpa.
