### ISSUE TITLE
Cyclic keymap interherence

### ISSUE THREAD

**Issue by xsrvmy** [ergoemacs/ergoemacs-mode#473]
I am currently trying to map M-w to a leader key in my .emacs file, and I am getting a cyclic interherence error, presumably due to the ergoemacs undefined binding. How do I unmap M-w in ergoemacs?

**Comment by mattfidler** [comment]
You should be able to do:

```lisp
(global-unset key (kbd "M-w"))
```

**Comment by mattfidler** [comment]
Reopen if you have issues on the new github version
