### ISSUE TITLE
Can't bind certain keys in custom themes

### ISSUE THREAD

**Issue by darkstego** [ergoemacs/ergoemacs-mode#475]
Undefined keys are bound to ergoemacs-undefined-key. But this binding happens even if theme specifies a keybinding. 

For example. I cannot bind "M-;" to anything because once emacs starts I will always get the message "Alt+; is disabled! Use Alt+' for comment-dwim instead". I cannot even use global-set-key in init.el to set it because ergoemacs overwrites it when it loads up.

An example is the "reduction" theme that comes with ergoemacs. It maps "M-;" yet you can't use it even if you load the theme because it ends up being disabled.

**Comment by mattfidler** [comment]
That's odd.  I use the reduction theme and don't have this behavior.  Can you tell me a bit more about how to reproduce this problem?

**Comment by darkstego** [comment]
I just pulled up my old config to tried to replicate it, but it is working fine now. I honestly don't know what was happening but I think it is safe to say it was a problem on my end. Sorry about that.

As an aside, I wanted to ask, why do you adjust the global-map rather than defining all bindings in a minor-mode keymap?
