### ISSUE TITLE
ido-mode breaks M-a on my install

### ISSUE THREAD

**Issue by cstjean** [ergoemacs/ergoemacs-mode#478]
On my install, whenever I enable ido-mode, `M-a` stops working. It says `Command smex not found`. My .emacs:

```
(package-initialize)
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)

(ido-mode 1)
```

On GNU Emacs 24.5.1, with ergoemacs-mode version 20180709.1345

Any help / work-around? ido-mode is super-convenient.

**Comment by mattfidler** [comment]
Sorry;  I haven't been that viligant.  You need to install `smex`, apparently.

**Comment by cstjean** [comment]
It works, thanks! That solves the issue for me.
