### ISSUE TITLE
Error when trying set "Customize Ctrl+C and Ctrl+X Cut/Copy Timeout" from menu

### ISSUE THREAD

**Issue by emakei** [ergoemacs/ergoemacs-mode#479]
Got error 

> Wrong number of arguments: (2 . 2), 1

 when choosing 

> Customize Ctrl+C and Ctrl+X Cut/Copy Timeout

from menu.

**Comment by mrDSide** [comment]
> I could not reproduce this. With emacs 26.1 on linux.

I use Emacs 26.1 on ubuntu (This is GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32) of 2019-01-26) and on windows. On both platforms same result. I don't made any configuration for ergoemacs-mode.

**Comment by mattfidler** [comment]
Are you using the ergoemacs-mode from github?

**Comment by mattfidler** [comment]
melpa stable or melpa unstable?

**Comment by mattfidler** [comment]
Reopen if you have issues on the new github version.  The current version goes back to cua-mode
