### ISSUE TITLE
Breaks `forward-button`, `push-button`, etc

### ISSUE THREAD

**Issue by spacekookie** [ergoemacs/ergoemacs-mode#484]
I'm using ergoemacs mode with the following initialisation:

```lisp
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil)
(setq ergoemacs-keyboard-layout "us")
(ergoemacs-mode 1)
```

This seems to break the `forward-button`, `push-button`, etc functions in emacs. Major modes like `notmuch-hello` no longer work when I have `ergoemacs` loaded. I'm not entirely sure why this would happen and am hoping you have some ideas about this

**Comment by wlandry** [comment]
It works for me.  I opened up the *Help* buffer for `make-text-button` and I was to use `forward-button` and `backwards-button`.  Are you still having a problem?
