### ISSUE TITLE
Parenthesis highlighting swallows next typed character (Macintosh/Emacs25/5.16.10.12)

### ISSUE THREAD

**Issue by mexon** [ergoemacs/ergoemacs-mode#485]
I'm using Emacs on Macintosh Catalina from emacsformacosx.com.  I'm comparing three versions: 24.5, 25.3, 26.3.  Of these, 24.3 works fine, 25.3 has a problem with parenthesis highlighting, and installing ergoemacs on 26.3 apparently causes Emacs to infinite loop.  So I'm describing 25.3 here.

Although I'm primarily using Macintosh Catalina here, I have also seen the same parenthesis problem on Ubuntu 18.04, so I think the problem isn't just my build.

I installed ergoemacs from Elpa, 5.16.10.12.  After installing, it is described like this: "ergoemacs-mode is an available obsolete package".  Nevertheless it seems to work.

If I edit a C file and start typing code, when I close a parenthesis the corresponding opening parenthesis is briefly highlighted.  If I wait until the highlighting disappears and then type a character it's fine.  But if I type another character while the highlighting is present, it de-highlights the opening parenthesis but does not insert the character.

If I use 25.3 without ergoemacs, it works fine.  While the parenthesis is highlighted, the next character is inserted as I'd expect.

See the attached video:

[Screen Recording 2019-11-02 at 16.01.33 .mov.zip](https://github.com/ergoemacs/ergoemacs-mode/files/3800608/Screen.Recording.2019-11-02.at.16.01.33.mov.zip)

**Comment by mattfidler** [comment]
Probably should be taken care of with the new release on github
