### ISSUE TITLE
`Invalid function` on F6

### ISSUE THREAD

**Issue by suhr** [ergoemacs/ergoemacs-mode#487]
`ergoemacs-command-loop--modal-p: Invalid function: (when (and (setq tmp (buffer-name)) (stringp tmp) (string-match reg tmp)) (throw (quote match-modal) t))`

Emacs version: `GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12)`.

ErgoEmacs version: 20190527.348 (melpa).

**Comment by mattfidler** [comment]
Should be ken care of with the new github version
