### ISSUE TITLE
Is it possible to have full ergoemacs without remaping the old shortcuts?

### ISSUE THREAD

**Issue by GrayJack** [ergoemacs/ergoemacs-mode#491]
I noticed that all functions that receives a new bind for the ergoemacs are remaped by `ergomemacs-map-undefined`. I would like that the old keys were not remaped. Is that possible?

**Comment by mattfidler** [comment]
It is, you can change the components to stop removing the old keys:

If you go to `ergoemacs-themes` change everything so it doesn't have `global-unset-key`

If you do it and add another `ergoemacs-component` without the `global-unset-key` you can make your own theme.
