### ISSUE TITLE
Map M-b to switch-buffer and M-B to ibuffer?

### ISSUE THREAD

**Issue by wlandry** [ergoemacs/ergoemacs-mode#501]
Right now, there is no single key combo to switch buffers unless you are using the Menu or Apps key.  Not everyone has one of those keys.  Switching buffers feels like that is something that is common enough to deserve a shortcut.  Would you be open to mapping M-b to switch-buffer?  I also was thinking of mapping M-B to ibuffer.

This would necessitate getting rid of the current binding to avy-
goto-word-or-subword-1.  But not everyone has avy, so it feels weird to take over a key binding for avy.  Also, avy already recommends using C-:, which is undefined in ergoemacs.  

In any event, if you agree, I can make a patch.  Please let me know. Thanks.

**Comment by mattfidler** [comment]
Hi @wlandry 

I think it is fine.  I suggest you make your own "theme".  People can be unhappy about changing keys.

**Comment by mattfidler** [comment]
I also don't have time to work on ergoemacs-mode anymore, if you want you can be a maintainer (ie merge your own commits).

What do you think.

**Comment by wlandry** [comment]
As I understand your offer, you are saying that my commits would not need to be vetted, but you still make the final decisions.  That is fine with me.  I think I know what kind of changes are not controversial.

For this change in particular, it is easy enough for me to have a local binding.  It does not merit its own theme inside ergoemacs, but is only worthwhile inside the 'standard' theme.  Thanks.

**Comment by mattfidler** [comment]
Yes
