### ISSUE TITLE
Use 'when' argument for make-obsolete & friends

### ISSUE THREAD

**Issue by abstern** [ergoemacs/ergoemacs-mode#503]
In Emacs 28, the `when` argument to `make-obsolete` and its friends `make-obsolete-variable`, `define-obsolete-function-alias`, `define-obsolete-variable-alias`, `define-obsolete-face-alias` is no longer optional, breaking `ergoemacs-mode`. Supplying the argument should fix the issue.

**Comment by mattfidler** [comment]
If you wish to add a pull request, feel free.  I'm still using emacs 26.
