### ISSUE TITLE
term-mode problems with `C-d` and error messages

### ISSUE THREAD

**Issue by wlandry** [ergoemacs/ergoemacs-mode#510]
I figured that I should create a new ticket rather than continuing to discuss this in #505.

As of `683020a92bbcb4a9135f277c6e90a338a49f224e`, in term mode, typing `C-d` gives me the message

    C-d is undefined

It should pass it on to the terminal, the same as with default Emacs.  This happens with both colemak and regular bindings.

Also, if I type `C-c o` to switch to a different buffer, I get the odd error message `C-x is undefined`.  This actually happens for a number of commands.  I get the same problem if I run with or without cua keys enabled.

If I switch to a different buffer with the mouse and then switch back, then `C-d` works and sends it on to the terminal.  So it feels like something is not initialized properly.  `C-c o` also starts to work, but `C-c 4` does not.

**Comment by mattfidler** [comment]
This works for me (now).

**Comment by wlandry** [comment]
`C-d` and `C-c o` work now.  I was mistaken about `C-c 4`.  It is working properly.

But I am still having a weird problem with `term.

1. Starting from a fresh emacs with colemake bindings, I split `*scratch*` into two windows with `M-4`.
2. I run `M-x term` in one of these split windows.
3. Then type `M-r` three times to switch from the `term` window to `*scratch*`, back to `term`, and then back to `*scratch*`.
4. I lose all of the ergoemacs bindings.  For example, `M-u` no longer goes up.

**Comment by mattfidler** [comment]
Seems to work for me now

**Comment by wlandry** [comment]
Seems to work for me as well.  Thanks.
