### ISSUE TITLE
Apps/Menu key functionality

### ISSUE THREAD

**Issue by TinaRussell** [ergoemacs/ergoemacs-mode#511]
Any chance we’ll see the return of the Apps/Menu key functionality in ErgoEmacs? I’ve grown dependent on it over the years; I’m not really sure how to use Emacs without it :cold_sweat:

I mean the translation aspect (e.g. \<apps\> f s becomes C-c C-s) but also the custom shortcuts (e.g. \<apps\> n t activates `org-capture`).

**Comment by mattfidler** [comment]
Yes.  It is a available in reduction but it is an oversight that it wasnt
abailable in standard ergoemacs

**Comment by mattfidler** [comment]
Should be fixed in d719e7e

**Comment by TinaRussell** [comment]
Thank you very much!

Two things: the first is, is it just me, or have the definitions of “\<apps\> d” and “\<apps\> f” been reversed? I think \<apps\> d used to be unchorded C-x and \<apps\> f used to be unchorded C-c, but it seems to be the opposite now.

The second thing is that I used to define new definitions for the apps key using `ergoemacs-component` and `ergoemacs-theme`:
```
    (ergoemacs-component tina-keys ()
      "Tina’s keys"
      (global-set-key (kbd "<apps> n w") 'eww)
      (global-set-key (kbd "<apps> j") 'org-journal-new-entry)
      (define-key lisp-mode-shared-map (kbd "<apps> ’") (lambda () (interactive) (hydra-lispy-x/body))))

    (ergoemacs-theme tina ()
      "Tina’s modified theme for ErgoEmacs"
      :based-on standard
      :components '(tina-keys))

    (ergoemacs-set-default 'ergoemacs-theme "tina")
```
I’m wondering, now that `ergoemacs-component` is gone, what’s the best way to do this? Should I simply use `(ergoemacs-define-key ergoemacs-override-keymap`… etc. for each definition? (In that case, do I need to be concerned with `ergoemacs-mode-raw-term-keymap` as well? What about adding definitions to specific maps, like `lisp-mode-shared-map` above, is that still possible?)

Thanks!

**Comment by mattfidler** [comment]
Hi @TinaRussell,  

I have been putting the documentation below:

https://github.com/ergoemacs/ergoemacs-mode#changing-your-own-bindings

Right now,

```lisp
(define-key lisp-mode-shared-map (kbd "<apps> ’") (lambda () (interactive) (hydra-lispy-x/body))
```
Needs to be worked out.

**Comment by mattfidler** [comment]
I verified the keys were backwards (no wonder I kept mistyping).  I swapped them back.

**Comment by mattfidler** [comment]
Also this should work in `ergoemacs-mode` since `<menu> '` is not bound to any keys in the `ergoemacs-mode` keymap.

```lisp
(define-key lisp-mode-shared-map (kbd "<apps> ’") (lambda () (interactive) (hydra-lispy-x/body)))
```

**Comment by mattfidler** [comment]
I am assuming this works for you @TinaRussell.  If not feel free to open another issue.
