### ISSUE TITLE
C-f isearch is not incremental

### ISSUE THREAD

**Issue by sg2002** [ergoemacs/ergoemacs-mode#515]
Hello, Matt.

Finally got to check out the new version.

One thing that I've noticed is that if you try to run isearch on C-f it's not incremental, unlike M-;, it just finds the first candidate, but you can't move further with it.

Not sure if it's intended, so decided to fill it here.

Also M-; isearch keybinding is not shown in [they layout picture](http://ergoemacs.github.io/ergoemacs-extras/ergo-layouts/ergoemacs-layout-us.png).

**Comment by mattfidler** [comment]
I added the `C-f` binding in He current ergoemacs-mode

**Comment by mattfidler** [comment]
You can see the binding by `ergoemacs-theme-describe`.  

I am unsure if I am going to update the website or not.
