### ISSUE TITLE
spurious bracket characters due to focus events, failure to handle xterm-paste

### ISSUE THREAD

**Issue by pdg137** [ergoemacs/ergoemacs-mode#520]
I'm running Windows Terminal with a msys2 shell, ssh to Ubuntu 22.04 with Emacs 27.1 and ergoemacs-mode-5.16.10.12.

TERM is `xterm-256color`.

In this configuration `emacs -q` seems to ignore focus/unfocus events (from e.g. Alt+Tab) and can accept a paste from the Windows OS with Ctrl+V.

However, a minimal ergoemacs configuration breaks on both kinds of events. The focus events move the cursor around and insert `[` characters, while Ctrl+V generates a message about xterm-paste being unbound:

![image](https://user-images.githubusercontent.com/466760/211186472-0443d0cf-48b3-46d7-9ac5-ef8f6a9795ea.png)

Some info about terminal focus events is here: https://github.com/veelenga/terminal-focus-reporting.el

I think the desired behavior would be to
* either disable / ignore terminal focus events or bind them to the appropriate emacs commands
* accept xterm-paste

**Comment by pdg137** [comment]
In case it helps, you can work around the problem by calling the function `terminal-focus-reporting--deactivate` from that package after emacs is loaded.  But it only works after loading, not in `init.el`.

**Comment by pdg137** [comment]
I just realized I was stuck on an old version.

This stuff works fine on `ergoemacs-mode-5.22.2.23`.

**Comment by mattfidler** [comment]
Awesome! Thanks for figuring it out
